import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'alb' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations = {
  en: {
    // Common
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.filter': 'Filter',
    'common.view': 'View',
    'common.deleting': 'Deleting...',
    // Images
    'images.noImages': 'No images',
    'images.notSpecified': 'Not specified',
    'images.propertyId': 'Property ID: {{id}}',
    'images.clientId': 'Client ID: {{id}}',
    'images.agentId': 'Agent ID: {{id}}',
    'images.propertyAddress': 'Property Address',
    'images.clientName': 'Client Name',
    'images.agentName': 'Agent Name',
    // Network
    'network.online': 'Online',
    'network.offline': 'Offline',
    'network.pendingSync': '{{count}} pending sync',
    'network.syncing': 'Syncing...',
    'network.sync': 'Sync',
    'network.lastSync': 'Last sync: {{time}}',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.reports': 'Reports',
    'nav.schedules': 'Schedules',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your app preferences',
    'settings.profile': 'Profile',
    'settings.appPreferences': 'App Preferences',
    'settings.dataManagement': 'Data Management',
    'settings.supportLegal': 'Support & Legal',
    'settings.account': 'Account',
    'settings.language': 'Language',
    'settings.languageSubtitle': 'Choose your preferred language',
    'settings.notifications': 'Notifications',
    'settings.notificationsSubtitle': 'Receive inspection reminders and updates',
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotificationsSubtitle': 'Receive inspection reminders and updates',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsSubtitle': 'Receive inspection reminders and updates via email',
    'settings.autoSync': 'Auto Sync',
    'settings.autoSyncSubtitle': 'Automatically sync data when online',
    'settings.darkMode': 'Dark Mode',
    'settings.darkModeSubtitle': 'Switch to dark theme',
    'settings.biometric': 'Biometric Login',
    'settings.biometricSubtitle': 'Use fingerprint or face ID to login',
    'settings.biometricLogin': 'Biometric Login',
    'settings.biometricLoginSubtitle': 'Use fingerprint or face ID to login',
    'settings.exportData': 'Export Data',
    'settings.exportDataSubtitle': 'Download all your inspection data',
    'settings.storageUsage': 'Storage Usage',
    'settings.storageUsageSubtitle': '2.3 GB used of 5 GB available',
    'settings.clearCache': 'Clear Cache',
    'settings.clearCacheSubtitle': 'Free up storage space',
    'settings.helpSupport': 'Help & Support',
    'settings.helpSupportSubtitle': 'Get help with the app',
    'settings.about': 'About',
    'settings.aboutSubtitle': 'Version 1.0.0',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.privacyPolicySubtitle': 'Read our privacy policy',
    'settings.termsOfService': 'Terms of Service',
    'settings.termsOfServiceSubtitle': 'Read our terms of service',
    'settings.logout': 'Logout',
    'settings.logoutSubtitle': 'Sign out of your account',
    'settings.appName': 'Property Inspection App',
    'settings.appVersion': 'Version 1.0.0 • Made by Vorbulla',
    
    // Language names
    'language.english': 'English',
    'language.albanian': 'Albanian',
    'language.german': 'German',
    
    // Alerts
    'alert.logout': 'Logout',
    'alert.logoutMessage': 'Are you sure you want to logout?',
    'alert.exportData': 'Export Data',
    'alert.exportDataMessage': 'This will export all your inspection data to a CSV file.',
    'alert.exportSuccess': 'Data exported successfully!',
    'alert.clearCache': 'Clear Cache',
    'alert.clearCacheMessage': 'This will clear all cached data and free up storage space.',
    'alert.clearCacheSuccess': 'Cache cleared successfully!',
    'alert.about': 'About',
    'alert.aboutMessage': 'Property Inspection App v1.0.0\nBuilt with React Native',
    'alert.storage': 'Storage',
    'alert.storageMessage': 'Manage your storage usage',
    
    // Login
    'login.title': 'Property Inspector',
    'login.subtitle': 'Sign in to start your inspections',
    'login.email': 'Email',
    'login.emailPlaceholder': 'Enter your email',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.signIn': 'Sign In',
    'login.error': 'Error',
    'login.fillFields': 'Please fill in all fields',
    'login.failed': 'Login Failed',
    'login.tryAgain': 'Login failed. Please try again.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Manage your inspections',
    'dashboard.searchPlaceholder': 'Search inspections...',
    'dashboard.moveInInspection': 'Move-in Inspection',
    'dashboard.moveOutInspection': 'Move-out Inspection', 
    'dashboard.periodicInspection': 'Periodic Inspection',
    'dashboard.maintenanceInspection': 'Maintenance Inspection',
    'dashboard.today': 'Today',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.inProgress': 'In Progress',
    'dashboard.completed': 'Completed',
    'dashboard.cancelled': 'Cancelled',
    'dashboard.noInspections': 'No inspections found',
    'dashboard.noInspectionsMessage': 'Start by creating your first inspection',
    'dashboard.goodMorning': 'Good morning,',
    'dashboard.all': 'All',
    'dashboard.tryAdjustingSearch': 'Try adjusting your search',
    'dashboard.overview': 'Overview',
    'dashboard.totalReports': 'Total Reports',
    'dashboard.draftReports': 'Draft Reports',
    'dashboard.recentReports': 'Recent Reports',
    'dashboard.viewAll': 'View All',
    'dashboard.filterInspections': 'Filter Inspections',
    'dashboard.noReports': 'No reports found',
    'dashboard.noReportsMessage': 'Create your first report to get started',
    'dashboard.scheduleInspection': 'Schedule Inspection',
    // Reports 
    'reports.subtitle': 'Manage inspection reports',
    'reports.searchPlaceholder': 'Search reports...',
    'reports.allTypes': 'All Types',
    'reports.noReports': 'No reports generated yet',
    'reports.noReportsMessage': 'Create your first report to get started',
    'reports.reportDetails': 'Report Details',
    'reports.reportInformation': 'Report Information',
    'reports.propertyDetails': 'Property Details',
    'reports.peopleInvolved': 'People Involved',
    'reports.inspectionDetails': 'Inspection Details',
    'reports.inspectionImages': 'Inspection Images',
    'reports.title': 'Title',
    'reports.type': 'Type',
    'reports.status': 'Status',
    'reports.date': 'Date',
    'reports.property': 'Property',
    'reports.client': 'Client',
    'reports.agent': 'Agent',
    'reports.email': 'Email',
    'reports.sendReportViaEmail': 'Send Report via Email',
    'reports.sendEmailConfirmation': 'Are you sure you want to send "{{title}}" via email?',
    'reports.sendEmail': 'Send Email',
    'reports.reportCreatedSuccessfully': 'Report Created Successfully',
    'reports.reportGeneratedMessage': 'Your inspection report has been generated and saved successfully.',
    'reports.failedToRefreshList': 'Failed to refresh reports list. Please check manually.',
    'reports.reportsRefreshed': 'Reports Refreshed',
    'reports.reportsListUpdated': 'Reports list has been updated successfully.',
    'reports.refreshError': 'Refresh Error',
    'reports.failedToRefresh': 'Failed to refresh reports. Please try again.',
    'reports.reportDataNotFound': 'Report data not found',
    'reports.noEmailAvailable': 'No email available',
    'reports.failedToLoadEmailData': 'Failed to load email data',
    'reports.emailSentSuccessfully': 'Email Sent Successfully',
    'reports.emailSentMessage': 'Your report has been sent via email to the agent and client.',
    'reports.failedToSendEmails': 'Failed to send emails',
    'reports.failedToSendEmailsWithConnection': 'Failed to send emails. Please check your connection and try again.',
    'reports.reportNotFound': 'Report not found',
    'reports.loadingReportDetails': 'Loading report details...',
    'reports.securityDeposit': 'Security Deposit',
    'reports.amount': 'Amount:',
    'reports.paymentMethod': 'Payment Method:',
    'reports.notes': 'Notes:',
    'reports.noInspectionDataAvailable': 'No inspection data available',
    'reports.contentType': 'Content Type:',
    'reports.contentExistsNoData': 'Content exists but no inspection data',
    'reports.noContentFound': 'No content found',
    'reports.contentKeys': 'Content Keys:',
    'reports.loadFailed': 'Load Failed',
    'reports.invalidUri': 'Invalid URI',
    'reports.emailRecipients': 'Email Recipients',
    'reports.agentEmailLabel': 'Agent Email',
    'reports.clientEmailLabel': 'Client Email',
    'reports.emailWarningMessage': 'This action will send the report to both recipients. Please ensure the email addresses are correct.',
    'reports.processing': 'Processing...',
    'reports.confirmAction': 'Confirm Action',
    'reports.confirmActionSubtitle': 'Are you sure you want to proceed?',
    // Common actions
    'common.complete': 'Complete',
    'common.completing': 'Completing...',
    'common.cancelling': 'Cancelling...',
    
    // Schedules
    'schedules.title': 'Schedules',
    'schedules.subtitle': 'Manage inspection appointments',
    'schedules.loadingInspections': 'Loading inspections...',
    'schedules.noInspections': 'No inspections assigned to you',
    'schedules.noInspectionsMessage': 'You don\'t have any inspections scheduled for this date',
    'schedules.cancelInspection': 'Cancel Inspection',
    'schedules.cancelInspectionMessage': 'Are you sure you want to cancel this inspection?',
    'schedules.markCompleted': 'Mark as Completed',
    'schedules.markCompletedMessage': 'Are you sure you want to mark this inspection as completed?',
    'schedules.inspectionCancelled': 'Inspection cancelled successfully',
    'schedules.inspectionCompleted': 'Inspection marked as completed successfully',
    'schedules.failedToCancel': 'Failed to cancel inspection',
    'schedules.failedToComplete': 'Failed to mark inspection as completed',
    'schedules.failedToLoad': 'Failed to load inspections',
    'schedules.failedToLoadDetails': 'Failed to load inspection details',
    'schedules.client': 'Client',
    'schedules.agent': 'Agent',
    'schedules.property': 'Property',
    'schedules.inspection': 'Inspection',
    'schedules.overdue': 'Overdue',
    'schedules.scheduled': 'Scheduled',
    'schedules.inProgress': 'In Progress',
    'schedules.pending': 'Pending',
    'schedules.completed': 'Completed',
    'schedules.cancelled': 'Cancelled',
    
    // Calendar
    'calendar.january': 'January',
    'calendar.february': 'February',
    'calendar.march': 'March',
    'calendar.april': 'April',
    'calendar.may': 'May',
    'calendar.june': 'June',
    'calendar.july': 'July',
    'calendar.august': 'August',
    'calendar.september': 'September',
    'calendar.october': 'October',
    'calendar.november': 'November',
    'calendar.december': 'December',
    'calendar.sunday': 'Sun',
    'calendar.monday': 'Mon',
    'calendar.tuesday': 'Tue',
    'calendar.wednesday': 'Wed',
    'calendar.thursday': 'Thu',
    'calendar.friday': 'Fri',
    'calendar.saturday': 'Sat',
    
    // Profile Screen
    'profile.inspections': 'Inspections',
    'profile.properties': 'Properties',
    'profile.reports': 'Reports',
    'profile.changePassword': 'Change Password',
    'profile.changePasswordSubtitle': 'Update your account password',
    'profile.passwordChanged': 'Password Changed',
    'profile.passwordChangedMessage': 'Your password has been changed successfully. You will be logged out for security reasons.',
    'profile.ok': 'OK',
    
    // Change Password Modal
    'password.title': 'Change Password',
    'password.currentPassword': 'Current Password',
    'password.newPassword': 'New Password',
    'password.confirmPassword': 'Confirm New Password',
    'password.currentPasswordPlaceholder': 'Enter your current password',
    'password.newPasswordPlaceholder': 'Enter your new password',
    'password.confirmPasswordPlaceholder': 'Confirm your new password',
    'password.currentPasswordRequired': 'Current password is required',
    'password.newPasswordRequired': 'New password is required',
    'password.confirmPasswordRequired': 'Please confirm your new password',
    'password.passwordsDoNotMatch': 'Passwords do not match',
    'password.passwordChangedSuccessfully': 'Password changed successfully',
    'password.failedToChangePassword': 'Failed to change password',
    'password.unexpectedError': 'An unexpected error occurred',
    'password.weak': 'Weak',
    'password.medium': 'Medium',
    'password.strong': 'Strong',
    'password.requirements': 'Password Requirements:',
    'password.securityNote': 'For security reasons, you will be logged out after changing your password. Please log in again with your new password.',
    'password.changePassword': 'Change Password',
    
    // Generate Report Modal
    'report.generate': 'Generate Report',
    'report.selectProperty': 'Select Property',
    'report.selectAgentClient': 'Select Agent & Client',
    'report.reportDetails': 'Report Details',
    'report.step': 'Step {{current}} of {{total}}',
    'report.complete': '{{percentage}}% Complete',
    'report.previous': 'Previous',
    'report.next': 'Next',
    'report.cancel': 'Cancel',
    'report.generateReport': 'Generate Report',
    'report.loadingProperties': 'Loading properties...',
    'report.loadingAgents': 'Loading agents...',
    'report.loadingClients': 'Loading clients...',
    'report.noProperties': 'No Properties Found',
    'report.noPropertiesMessage': 'You need to add properties first before generating reports. Please go to the Properties section to add some properties.',
    'report.goToProperties': 'Go to Properties',
    'report.addProperties': 'Add Properties',
    'report.addPropertiesMessage': 'Please go to the Properties section in the main app to add properties first.',
    'report.selectAgent': 'Select Agent *',
    'report.selectClient': 'Select Client *',
    'report.currentAgent': 'Current Agent',
    'report.noAgents': 'No Agents Found',
    'report.noAgentsMessage': 'No agents available. Please contact your administrator.',
    'report.noClients': 'No Clients Found',
    'report.noClientsMessage': 'No clients available. Please add clients first.',
    'report.reportTitle': 'Report Title *',
    'report.reportTitlePlaceholder': 'Enter report title...',
    'report.database': 'Database: {{name}}',
    'report.owner': 'Owner: {{name}}',
    'report.you': ' (You)',
    'report.validationError': 'Validation Error',
    'report.selectPropertyFirst': 'Please select a property before proceeding',
    'report.selectAgentClientFirst': 'Please select both an agent and a client before proceeding',
    'report.enterTitleFirst': 'Please enter a report title before proceeding',
    'report.completeRequiredFields': 'Please complete all required fields before generating the report',
    'report.generatedSuccessfully': 'Report generated successfully!',
    'report.failedToGenerate': 'Failed to generate report',
    'report.failedToLoadProperties': 'Failed to load properties: {{error}}',
    'report.failedToLoadAgents': 'Failed to load agents: {{error}}',
    'report.failedToLoadClients': 'Failed to load clients: {{error}}',
    'report.errorRendering': 'Error rendering step content',
    'report.errorRenderingModal': 'An error occurred while rendering the modal',
    'report.errorProceeding': 'An error occurred while proceeding to the next step: {{error}}',
    'report.propertyNotFoundError': 'The selected property could not be found. Please try selecting a different property or contact support.',
    'report.clientNotFoundError': 'The selected client could not be found. Please try selecting a different client or contact support.',
    'report.missingFieldsError': 'Please ensure all required fields are filled out correctly.',
    
    // Inspection Areas
    'inspection.exterior': 'Exterior',
    'inspection.interior': 'Interior',
    'inspection.electrical': 'Electrical',
    'inspection.plumbing': 'Plumbing',
    'inspection.hvac': 'HVAC',
    'inspection.safety': 'Safety',
    'inspection.exteriorInspection': 'Exterior Inspection',
    'inspection.interiorInspection': 'Interior Inspection',
    'inspection.electricalInspection': 'Electrical Inspection',
    'inspection.plumbingInspection': 'Plumbing Inspection',
    'inspection.hvacInspection': 'HVAC Inspection',
    'inspection.safetyInspection': 'Safety Inspection',
    
    // Inspection Fields
    'inspection.roofCondition': 'Roof Condition',
    'inspection.roofImages': 'Roof Images',
    'inspection.sidingCondition': 'Siding Condition',
    'inspection.sidingImages': 'Siding Images',
    'inspection.windowsDoors': 'Windows & Doors',
    'inspection.windowsImages': 'Windows Images',
    'inspection.foundation': 'Foundation',
    'inspection.foundationImages': 'Foundation Images',
    'inspection.exteriorNotes': 'Exterior Notes',
    'inspection.wallsCondition': 'Walls Condition',
    'inspection.wallsImages': 'Walls Images',
    'inspection.floorsCondition': 'Floors Condition',
    'inspection.floorsImages': 'Floors Images',
    'inspection.ceilingsCondition': 'Ceilings Condition',
    'inspection.ceilingsImages': 'Ceilings Images',
    'inspection.interiorNotes': 'Interior Notes',
    'inspection.electricalSystem': 'Electrical System',
    'inspection.electricalSystemImages': 'Electrical System Images',
    'inspection.outletsSwitches': 'Outlets & Switches',
    'inspection.outletsImages': 'Outlets Images',
    'inspection.lighting': 'Lighting',
    'inspection.lightingImages': 'Lighting Images',
    'inspection.electricalNotes': 'Electrical Notes',
    'inspection.waterSupply': 'Water Supply',
    'inspection.waterSupplyImages': 'Water Supply Images',
    'inspection.drainage': 'Drainage',
    'inspection.drainageImages': 'Drainage Images',
    'inspection.fixtures': 'Fixtures',
    'inspection.fixturesImages': 'Fixtures Images',
    'inspection.plumbingNotes': 'Plumbing Notes',
    'inspection.heatingSystem': 'Heating System',
    'inspection.heatingSystemImages': 'Heating System Images',
    'inspection.coolingSystem': 'Cooling System',
    'inspection.coolingSystemImages': 'Cooling System Images',
    'inspection.ventilation': 'Ventilation',
    'inspection.ventilationImages': 'Ventilation Images',
    'inspection.hvacNotes': 'HVAC Notes',
    'inspection.smokeDetectors': 'Smoke Detectors',
    'inspection.smokeDetectorsImages': 'Smoke Detectors Images',
    'inspection.carbonMonoxide': 'Carbon Monoxide Detectors',
    'inspection.carbonMonoxideImages': 'Carbon Monoxide Images',
    'inspection.fireExtinguisher': 'Fire Extinguisher',
    'inspection.fireExtinguisherImages': 'Fire Extinguisher Images',
    'inspection.safetyNotes': 'Safety Notes',
    
    // Inspection Options
    'inspection.none': 'None',
    'inspection.excellent': 'Excellent',
    'inspection.good': 'Good',
    'inspection.fair': 'Fair',
    'inspection.poor': 'Poor',
    'inspection.needsReplacement': 'Needs Replacement',
    'inspection.needsRepair': 'Needs Repair',
    'inspection.needsUpgrade': 'Needs Upgrade',
    'inspection.presentWorking': 'Present & Working',
    'inspection.presentNeedsBattery': 'Present - Needs Battery',
    'inspection.missing': 'Missing',
    'inspection.notTested': 'Not Tested',
    'inspection.presentCurrent': 'Present & Current',
    'inspection.presentExpired': 'Present - Expired',
    
    // Placeholders
    'inspection.enterField': 'Enter {{field}}...',
    
    // Inspection Completion Modal
    'inspectionCompletion.title': 'Complete Inspection',
    'inspectionCompletion.propertyDetails': 'Property Details',
    'inspectionCompletion.peopleInvolved': 'People Involved',
    'inspectionCompletion.inspectionSummary': 'Inspection Summary',
    'inspectionCompletion.summary': 'Summary',
    'inspectionCompletion.summaryPlaceholder': 'Enter inspection summary...',
    'inspectionCompletion.previous': 'Previous',
    'inspectionCompletion.next': 'Next',
    'inspectionCompletion.cancel': 'Cancel',
    'inspectionCompletion.completeInspection': 'Complete Inspection',
    'inspectionCompletion.step': 'Step {{current}} of {{total}}',
    'inspectionCompletion.complete': '{{percentage}}% Complete',
    'inspectionCompletion.validationError': 'Validation Error',
    'inspectionCompletion.enterSummaryFirst': 'Please enter an inspection summary before proceeding',
    'inspectionCompletion.completeRequiredFields': 'Please complete the following required fields: {{fields}}',
    'inspectionCompletion.completeRequiredFieldsBeforeSubmit': 'Please complete the following required fields before submitting:\n\n{{fields}}',
    'inspectionCompletion.completeSummaryBeforeSubmit': 'Please complete the inspection summary before submitting',
    'inspectionCompletion.success': 'Success',
    'inspectionCompletion.completedSuccessfully': 'Inspection completed and report generated successfully!',
    'inspectionCompletion.failedToComplete': 'Failed to complete inspection',
    'inspectionCompletion.property': 'Property',
    'inspectionCompletion.address': 'Address',
    'inspectionCompletion.type': 'Type',
    'inspectionCompletion.size': 'Size',
    'inspectionCompletion.client': 'Client',
    'inspectionCompletion.agent': 'Agent',
    'inspectionCompletion.name': 'Name',
    'inspectionCompletion.email': 'Email',
    'inspectionCompletion.phone': 'Phone',
    'inspectionCompletion.inspection': 'Inspection',
    'inspectionCompletion.addImage': 'Add Image',
    'inspectionCompletion.selectImageSource': 'Select Image Source',
    'inspectionCompletion.chooseImageSource': 'Choose how you want to add an image',
    'inspectionCompletion.camera': 'Camera',
    'inspectionCompletion.gallery': 'Gallery',
    'inspectionCompletion.cameraPermissionDenied': 'Camera permission is required to take photos',
    
    // Inspection
    'inspection.inspection': 'Inspection',
    
    // Signature
    'signature.title': 'Signatures',
    'signature.signatures': 'Signatures',
    'signature.agentSignature': 'Agent Signature',
    'signature.clientSignature': 'Client Signature',
    'signature.agentName': 'Agent: {{name}}',
    'signature.clientName': 'Client: {{name}}',
    'signature.agent': 'Agent',
    'signature.client': 'Client',
    'signature.note': 'Both signatures are required to generate the report',
    'signature.missingSignatures': 'Please complete the following signatures: {{signatures}}',
    'signature.captured': 'Signature Captured',
    'signature.signHere': 'Sign here',
    'signature.clear': 'Clear',
    'signature.save': 'Save',
    'signature.processing': 'Processing...',
  },
  alb: {
    // Common
    'common.cancel': 'Anulo',
    'common.save': 'Ruaj',
    'common.delete': 'Fshi',
    'common.edit': 'Ndrysho',
    'common.add': 'Shto',
    'common.loading': 'Duke ngarkuar...',
    'common.error': 'Gabim',
    'common.success': 'Sukses',
    'common.confirm': 'Konfirmo',
    'common.yes': 'Po',
    'common.no': 'Jo',
    'common.filter': 'Filter',
    'common.view': 'Shiko',
    'common.deleting': 'Po fshihet...',
    // Images
    'images.noImages': 'Nuk ka imazhe',
    'images.notSpecified': 'Nuk është specifikuar',
    'images.propertyId': 'ID e Pronës: {{id}}',
    'images.clientId': 'ID e Klientit: {{id}}',
    'images.agentId': 'ID e Agjentit: {{id}}',
    'images.propertyAddress': 'Adresa e Pronës',
    'images.clientName': 'Emri i Klientit',
    'images.agentName': 'Emri i Agjentit',
    
    // Network
    'network.online': 'Online',
    'network.offline': 'Offline',
    'network.pendingSync': '{{count}} sinkronizim në pritje',
    'network.syncing': 'Duke sinkronizuar...',
    'network.sync': 'Sinkronizo',
    'network.lastSync': 'Sinkronizimi i fundit: {{time}}',
    
    // Navigation
    'nav.dashboard': 'Paneli',
    'nav.reports': 'Raportet',
    'nav.schedules': 'Orari',
    'nav.profile': 'Profili',
    'nav.settings': 'Cilësimet',
    
    // Settings
    'settings.title': 'Cilësimet',
    'settings.subtitle': 'Menaxho preferencat e aplikacionit',
    'settings.profile': 'Profili',
    'settings.appPreferences': 'Preferencat e Aplikacionit',
    'settings.dataManagement': 'Menaxhimi i të Dhënave',
    'settings.supportLegal': 'Mbështetja dhe Ligjore',
    'settings.account': 'Llogaria',
    'settings.language': 'Gjuha',
    'settings.languageSubtitle': 'Zgjidh gjuhën e preferuar',
    'settings.notifications': 'Njoftimet',
    'settings.notificationsSubtitle': 'Merr kujtime për inspektime dhe përditësime',
    'settings.pushNotifications': 'Njoftimet Push',
    'settings.pushNotificationsSubtitle': 'Merr kujtime për inspektime dhe përditësime',
    'settings.emailNotifications': 'Njoftimet Email',
    'settings.emailNotificationsSubtitle': 'Merr kujtime për inspektime dhe përditësime përmes email',
    'settings.autoSync': 'Sinkronizimi Automatik',
    'settings.autoSyncSubtitle': 'Sinkronizo automatikisht të dhënat kur jesh online',
    'settings.darkMode': 'Modaliteti i Errët', 
    'settings.darkModeSubtitle': 'Kalo në temën e errët',
    'settings.biometric': 'Hyrja Biometrike',
    'settings.biometricSubtitle': 'Përdor gjurmën e gishtit ose ID-në e fytyrës për të hyrë',
    'settings.biometricLogin': 'Hyrja Biometrike',
    'settings.biometricLoginSubtitle': 'Përdor gjurmën e gishtit ose ID-në e fytyrës për të hyrë',
    'settings.exportData': 'Eksporto të Dhënat',
    'settings.exportDataSubtitle': 'Shkarko të gjitha të dhënat e inspektimeve',
    'settings.storageUsage': 'Përdorimi i Ruajtjes',
    'settings.storageUsageSubtitle': '2.3 GB të përdorura nga 5 GB të disponueshme',
    'settings.clearCache': 'Pastro Cache',
    'settings.clearCacheSubtitle': 'Liro hapësirë ruajtjeje',
    'settings.helpSupport': 'Ndihmë dhe Mbështetje',
    'settings.helpSupportSubtitle': 'Merr ndihmë me aplikacionin',
    'settings.about': 'Rreth',
    'settings.aboutSubtitle': 'Versioni 1.0.0',
    'settings.privacyPolicy': 'Politika e Privatësisë',
    'settings.privacyPolicySubtitle': 'Lexo politikën tonë të privatësisë',
    'settings.termsOfService': 'Kushtet e Shërbimit',
    'settings.termsOfServiceSubtitle': 'Lexo kushtet tona të shërbimit',
    'settings.logout': 'Dil',
    'settings.logoutSubtitle': 'Dil nga llogaria jote',
    'settings.appName': 'Aplikacioni i Inspektimit të Pronave',
    'settings.appVersion': 'Versioni 1.0.0 • Bërë nga Vorbulla',
    
    // Language names
    'language.english': 'Anglisht',
    'language.albanian': 'Shqip',
    'language.german': 'Gjermanisht',
    
    // Alerts
    'alert.logout': 'Dil',
    'alert.logoutMessage': 'A je i sigurt që dëshiron të dalësh?',
    'alert.exportData': 'Eksporto të Dhënat',
    'alert.exportDataMessage': 'Kjo do të eksportojë të gjitha të dhënat e inspektimeve në një skedar CSV.',
    'alert.exportSuccess': 'Të dhënat u eksportuan me sukses!',
    'alert.clearCache': 'Pastro Cache',
    'alert.clearCacheMessage': 'Kjo do të pastrojë të gjitha të dhënat e cache dhe do të lirojë hapësirë ruajtjeje.',
    'alert.clearCacheSuccess': 'Cache u pastrua me sukses!',
    'alert.about': 'Rreth',
    'alert.aboutMessage': 'Aplikacioni i Inspektimit të Pronave v1.0.0\nBërë me React Native',
    'alert.storage': 'Ruajtja',
    'alert.storageMessage': 'Menaxho përdorimin e ruajtjes',
    
    // Login
    'login.title': 'Inspektori i Pronave',
    'login.subtitle': 'Hyni për të filluar inspektimet tuaja',
    'login.email': 'Email',
    'login.emailPlaceholder': 'Shkruani email-in tuaj',
    'login.password': 'Fjalëkalimi',
    'login.passwordPlaceholder': 'Shkruani fjalëkalimin tuaj',
    'login.signIn': 'Hyni',
    'login.error': 'Gabim',
    'login.fillFields': 'Ju lutemi plotësoni të gjitha fushat',
    'login.failed': 'Hyrja Dështoi',
    'login.tryAgain': 'Hyrja dështoi. Ju lutemi provoni përsëri.',
    
    // Dashboard
    'dashboard.title': 'Paneli',
    'dashboard.subtitle': 'Menaxho inspektimet tuaja',
    'dashboard.searchPlaceholder': 'Kërko inspektime...',
    'dashboard.moveInInspection': 'Inspektimi i Hyrjes',
    'dashboard.moveOutInspection': 'Inspektimi i Daljes',
    'dashboard.periodicInspection': 'Inspektimi Periodik',
    'dashboard.maintenanceInspection': 'Inspektimi i Mirëmbajtjes',
    'dashboard.today': 'Sot',
    'dashboard.upcoming': 'Në Ardhje',
    'dashboard.inProgress': 'Në Progres',
    'dashboard.completed': 'Përfunduar',
    'dashboard.cancelled': 'Anuluar',
    'dashboard.noInspections': 'Nuk u gjetën inspektime',
    'dashboard.noInspectionsMessage': 'Fillo duke krijuar inspektimin tuaj të parë',
    'dashboard.goodMorning': 'Mirëmëngjes,',
    'dashboard.all': 'Të gjitha',
    'dashboard.tryAdjustingSearch': 'Provo të rregullosh kërkesën',
    'dashboard.overview': 'Përmbledhje',
    'dashboard.totalReports': 'Raportet Totale',
    'dashboard.draftReports': 'Raportet e Skicës',
    'dashboard.recentReports': 'Raportet e Fundit',
    'dashboard.viewAll': 'Shiko të Gjitha',
    'dashboard.filterInspections': 'Filtro Inspektimet',
    'dashboard.noReports': 'Nuk u gjeneruan raporte ende',
    'dashboard.noReportsMessage': 'Krijo raportin tuaj të parë për të filluar',
    'dashboard.scheduleInspection': 'Planifiko Inspektimin',
    // Reports
    'reports.subtitle': 'Menaxho raportet e inspektimit',
    'reports.searchPlaceholder': 'Kërko raporte...',
    'reports.allTypes': 'Të Gjitha Llojet',
    'reports.noReports': 'Nuk u gjeneruan raporte ende',
    'reports.noReportsMessage': 'Krijo raportin tuaj të parë për të filluar',
    'reports.reportDetails': 'Detajet e Raportit',
    'reports.reportInformation': 'Informacioni i Raportit',
    'reports.propertyDetails': 'Detajet e Pronës',
    'reports.peopleInvolved': 'Njerëzit e Përfshirë',
    'reports.inspectionDetails': 'Detajet e Inspektimit',
    'reports.inspectionImages': 'Imazhet e Inspektimit',
    'reports.title': 'Titulli',
    'reports.type': 'Lloji',
    'reports.status': 'Statusi',
    'reports.date': 'Data',
    'reports.property': 'Prona',
    'reports.client': 'Klienti',
    'reports.agent': 'Agjenti',
    'reports.email': 'Email',
    'reports.sendReportViaEmail': 'Dërgo Raportin përmes Email',
    'reports.sendEmailConfirmation': 'A je i sigurt që dëshiron të dërgosh "{{title}}" përmes email?',
    'reports.sendEmail': 'Dërgo Email',
    'reports.reportCreatedSuccessfully': 'Raporti u Kriua me Sukses',
    'reports.reportGeneratedMessage': 'Raporti juaj i inspektimit u gjenerua dhe u ruajt me sukses.',
    'reports.failedToRefreshList': 'Dështoi përditësimi i listës së raporteve. Ju lutemi kontrolloni manualisht.',
    'reports.reportsRefreshed': 'Raportet u Përditësuan',
    'reports.reportsListUpdated': 'Lista e raporteve u përditësua me sukses.',
    'reports.refreshError': 'Gabim Përditësimi',
    'reports.failedToRefresh': 'Dështoi përditësimi i raporteve. Ju lutemi provoni përsëri.',
    'reports.reportDataNotFound': 'Të dhënat e raportit nuk u gjetën',
    'reports.noEmailAvailable': 'Nuk ka email të disponueshëm',
    'reports.failedToLoadEmailData': 'Dështoi ngarkimi i të dhënave të email',
    'reports.emailSentSuccessfully': 'Email u Dërgua me Sukses',
    'reports.emailSentMessage': 'Raporti juaj u dërgua përmes email te agjenti dhe klienti.',
    'reports.failedToSendEmails': 'Dështoi dërgimi i emailave',
    'reports.failedToSendEmailsWithConnection': 'Dështoi dërgimi i emailave. Ju lutemi kontrolloni lidhjen dhe provoni përsëri.',
    'reports.reportNotFound': 'Raporti nuk u gjet',
    'reports.loadingReportDetails': 'Duke ngarkuar detajet e raportit...',
    'reports.securityDeposit': 'Depozita e Sigurisë',
    'reports.amount': 'Shuma:',
    'reports.paymentMethod': 'Metoda e Pagesës:',
    'reports.notes': 'Shënimet:',
    'reports.noInspectionDataAvailable': 'Nuk ka të dhëna inspektimi të disponueshme',
    'reports.contentType': 'Lloji i Përmbajtjes:',
    'reports.contentExistsNoData': 'Përmbajtja ekziston por nuk ka të dhëna inspektimi',
    'reports.noContentFound': 'Nuk u gjet përmbajtje',
    'reports.contentKeys': 'Çelësat e Përmbajtjes:',
    'reports.loadFailed': 'Ngarkesa Dështoi',
    'reports.invalidUri': 'URI e Pavlefshme',
    'reports.emailRecipients': 'Marrësit e Email',
    'reports.agentEmailLabel': 'Email i Agjentit',
    'reports.clientEmailLabel': 'Email i Klientit',
    'reports.emailWarningMessage': 'Ky veprim do të dërgojë raportin te të dy marrësit. Ju lutemi sigurohuni që adresat e email janë të sakta.',
    'reports.processing': 'Duke përpunuar...',
    'reports.confirmAction': 'Konfirmo Veprimin',
    'reports.confirmActionSubtitle': 'A je i sigurt që dëshiron të vazhdosh?',
    // Common actions
    'common.complete': 'Përfundo',
    'common.completing': 'Duke përfunduar...',
    'common.cancelling': 'Duke anuluar...',
    
    // Schedules
    'schedules.title': 'Orari',
    'schedules.subtitle': 'Menaxho takimet e inspektimit',
    'schedules.loadingInspections': 'Duke ngarkuar inspektimet...',
    'schedules.noInspections': 'Nuk keni inspektime të caktuara',
    'schedules.noInspectionsMessage': 'Nuk keni asnjë inspektim të planifikuar për këtë datë',
    'schedules.cancelInspection': 'Anulo Inspektimin',
    'schedules.cancelInspectionMessage': 'A je i sigurt që dëshiron të anulosh këtë inspektim?',
    'schedules.markCompleted': 'Shëno si të Përfunduar',
    'schedules.markCompletedMessage': 'A je i sigurt që dëshiron ta shënosh këtë inspektim si të përfunduar?',
    'schedules.inspectionCancelled': 'Inspektimi u anulua me sukses',
    'schedules.inspectionCompleted': 'Inspektimi u shënua si i përfunduar me sukses',
    'schedules.failedToCancel': 'Dështoi anulimi i inspektimit',
    'schedules.failedToComplete': 'Dështoi shënimi i inspektimit si i përfunduar',
    'schedules.failedToLoad': 'Dështoi ngarkimi i inspektimeve',
    'schedules.failedToLoadDetails': 'Dështoi ngarkimi i detajeve të inspektimit',
    'schedules.client': 'Klienti',
    'schedules.agent': 'Agjenti',
    'schedules.property': 'Prona',
    'schedules.inspection': 'Inspektimi',
    'schedules.overdue': 'I vonuar',
    'schedules.scheduled': 'I planifikuar',
    'schedules.inProgress': 'Në Progres',
    'schedules.pending': 'Në Pritje',
    'schedules.completed': 'I Përfunduar',
    'schedules.cancelled': 'I Anuluar',
    
    // Calendar
    'calendar.january': 'Janar',
    'calendar.february': 'Shkurt',
    'calendar.march': 'Mars',
    'calendar.april': 'Prill',
    'calendar.may': 'Maj',
    'calendar.june': 'Qershor',
    'calendar.july': 'Korrik',
    'calendar.august': 'Gusht',
    'calendar.september': 'Shtator',
    'calendar.october': 'Tetor',
    'calendar.november': 'Nëntor',
    'calendar.december': 'Dhjetor',
    'calendar.sunday': 'Die',
    'calendar.monday': 'Hën',
    'calendar.tuesday': 'Mar',
    'calendar.wednesday': 'Mër',
    'calendar.thursday': 'Enj',
    'calendar.friday': 'Pre',
    'calendar.saturday': 'Sht',
    
    // Profile Screen
    'profile.inspections': 'Inspektimet',
    'profile.properties': 'Pronat',
    'profile.reports': 'Raportet',
    'profile.changePassword': 'Ndrysho Fjalëkalimin',
    'profile.changePasswordSubtitle': 'Përditëso fjalëkalimin e llogarisë',
    'profile.passwordChanged': 'Fjalëkalimi u Ndryshua',
    'profile.passwordChangedMessage': 'Fjalëkalimi juaj u ndryshua me sukses. Do të dilni për arsye sigurie.',
    'profile.ok': 'OK',
    
    // Change Password Modal
    'password.title': 'Ndrysho Fjalëkalimin',
    'password.currentPassword': 'Fjalëkalimi Aktual',
    'password.newPassword': 'Fjalëkalimi i Ri',
    'password.confirmPassword': 'Konfirmo Fjalëkalimin e Ri',
    'password.currentPasswordPlaceholder': 'Shkruani fjalëkalimin tuaj aktual',
    'password.newPasswordPlaceholder': 'Shkruani fjalëkalimin tuaj të ri',
    'password.confirmPasswordPlaceholder': 'Konfirmoni fjalëkalimin tuaj të ri',
    'password.currentPasswordRequired': 'Fjalëkalimi aktual është i detyrueshëm',
    'password.newPasswordRequired': 'Fjalëkalimi i ri është i detyrueshëm',
    'password.confirmPasswordRequired': 'Ju lutemi konfirmoni fjalëkalimin tuaj të ri',
    'password.passwordsDoNotMatch': 'Fjalëkalimet nuk përputhen',
    'password.passwordChangedSuccessfully': 'Fjalëkalimi u ndryshua me sukses',
    'password.failedToChangePassword': 'Dështoi ndryshimi i fjalëkalimit',
    'password.unexpectedError': 'Ndodhi një gabim i papritur',
    'password.weak': 'I dobët',
    'password.medium': 'Mesatar',
    'password.strong': 'I fortë',
    'password.requirements': 'Kërkesat e Fjalëkalimit:',
    'password.securityNote': 'Për arsye sigurie, do të dilni pas ndryshimit të fjalëkalimit. Ju lutemi hyni përsëri me fjalëkalimin tuaj të ri.',
    'password.changePassword': 'Ndrysho Fjalëkalimin',
    
    // Generate Report Modal
    'report.generate': 'Gjenero Raportin',
    'report.selectProperty': 'Zgjidh Pronën',
    'report.selectAgentClient': 'Zgjidh Agjentin dhe Klientin',
    'report.reportDetails': 'Detajet e Raportit',
    'report.step': 'Hapi {{current}} nga {{total}}',
    'report.complete': '{{percentage}}% i Përfunduar',
    'report.previous': 'Mëparshëm',
    'report.next': 'Tjetër',
    'report.cancel': 'Anulo',
    'report.generateReport': 'Gjenero Raportin',
    'report.loadingProperties': 'Duke ngarkuar pronat...',
    'report.loadingAgents': 'Duke ngarkuar agjentët...',
    'report.loadingClients': 'Duke ngarkuar klientët...',
    'report.noProperties': 'Nuk u Gjetën Prona',
    'report.noPropertiesMessage': 'Duhet të shtoni pronat së pari para se të gjeneroni raporte. Ju lutemi shkoni te seksioni i Pronave për të shtuar disa prona.',
    'report.goToProperties': 'Shko te Pronat',
    'report.addProperties': 'Shto Prona',
    'report.addPropertiesMessage': 'Ju lutemi shkoni te seksioni i Pronave në aplikacionin kryesor për të shtuar prona së pari.',
    'report.selectAgent': 'Zgjidh Agjentin *',
    'report.selectClient': 'Zgjidh Klientin *',
    'report.currentAgent': 'Agjenti Aktual',
    'report.noAgents': 'Nuk u Gjetën Agjentë',
    'report.noAgentsMessage': 'Nuk ka agjentë të disponueshëm. Ju lutemi kontaktoni administratorin tuaj.',
    'report.noClients': 'Nuk u Gjetën Klientë',
    'report.noClientsMessage': 'Nuk ka klientë të disponueshëm. Ju lutemi shtoni klientë së pari.',
    'report.reportTitle': 'Titulli i Raportit *',
    'report.reportTitlePlaceholder': 'Shkruani titullin e raportit...',
    'report.database': 'Baza e të Dhënave: {{name}}',
    'report.owner': 'Pronari: {{name}}',
    'report.you': ' (Ti)',
    'report.validationError': 'Gabim Validimi',
    'report.selectPropertyFirst': 'Ju lutemi zgjidhni një pronë para se të vazhdoni',
    'report.selectAgentClientFirst': 'Ju lutemi zgjidhni si një agjent ashtu edhe një klient para se të vazhdoni',
    'report.enterTitleFirst': 'Ju lutemi shkruani një titull raporti para se të vazhdoni',
    'report.completeRequiredFields': 'Ju lutemi plotësoni të gjitha fushat e detyrueshme para se të gjeneroni raportin',
    'report.generatedSuccessfully': 'Raporti u gjenerua me sukses!',
    'report.failedToGenerate': 'Dështoi gjenerimi i raportit',
    'report.failedToLoadProperties': 'Dështoi ngarkimi i pronave: {{error}}',
    'report.failedToLoadAgents': 'Dështoi ngarkimi i agjentëve: {{error}}',
    'report.failedToLoadClients': 'Dështoi ngarkimi i klientëve: {{error}}',
    'report.errorRendering': 'Gabim në renderimin e përmbajtjes së hapit',
    'report.errorRenderingModal': 'Ndodhi një gabim gjatë renderimit të modales',
    'report.errorProceeding': 'Ndodhi një gabim gjatë vazhdimit në hapin tjetër: {{error}}',
    'report.propertyNotFoundError': 'Prona e zgjedhur nuk mund të gjendet. Ju lutemi provoni të zgjidhni një pronë tjetër ose kontaktoni mbështetjen.',
    'report.clientNotFoundError': 'Klienti i zgjedhur nuk mund të gjendet. Ju lutemi provoni të zgjidhni një klient tjetër ose kontaktoni mbështetjen.',
    'report.missingFieldsError': 'Ju lutemi sigurohuni që të gjitha fushat e detyrueshme janë plotësuar siç duhet.',
    
    // Inspection Areas
    'inspection.exterior': 'Jashtëm',
    'inspection.interior': 'Brendshëm',
    'inspection.electrical': 'Elektrik',
    'inspection.plumbing': 'Ujësjellës',
    'inspection.hvac': 'HVAC',
    'inspection.safety': 'Siguria',
    'inspection.exteriorInspection': 'Inspektimi i Jashtëm',
    'inspection.interiorInspection': 'Inspektimi i Brendshëm',
    'inspection.electricalInspection': 'Inspektimi Elektrik',
    'inspection.plumbingInspection': 'Inspektimi i Ujësjellësit',
    'inspection.hvacInspection': 'Inspektimi HVAC',
    'inspection.safetyInspection': 'Inspektimi i Sigurisë',
    
    // Inspection Fields
    'inspection.roofCondition': 'Gjendja e Çatisë',
    'inspection.roofImages': 'Imazhet e Çatisë',
    'inspection.sidingCondition': 'Gjendja e Façadës',
    'inspection.sidingImages': 'Imazhet e Façadës',
    'inspection.windowsDoors': 'Dritaret dhe Dyerat',
    'inspection.windowsImages': 'Imazhet e Dritareve',
    'inspection.foundation': 'Themeli',
    'inspection.foundationImages': 'Imazhet e Themelit',
    'inspection.exteriorNotes': 'Shënimet e Jashtme',
    'inspection.wallsCondition': 'Gjendja e Mureve',
    'inspection.wallsImages': 'Imazhet e Mureve',
    'inspection.floorsCondition': 'Gjendja e Dyshemeve',
    'inspection.floorsImages': 'Imazhet e Dyshemeve',
    'inspection.ceilingsCondition': 'Gjendja e Tavaneve',
    'inspection.ceilingsImages': 'Imazhet e Tavaneve',
    'inspection.interiorNotes': 'Shënimet e Brendshme',
    'inspection.electricalSystem': 'Sistemi Elektrik',
    'inspection.electricalSystemImages': 'Imazhet e Sistemit Elektrik',
    'inspection.outletsSwitches': 'Priza dhe Çelsat',
    'inspection.outletsImages': 'Imazhet e Prizave',
    'inspection.lighting': 'Ndriçimi',
    'inspection.lightingImages': 'Imazhet e Ndriçimit',
    'inspection.electricalNotes': 'Shënimet Elektrike',
    'inspection.waterSupply': 'Furnizimi me Ujë',
    'inspection.waterSupplyImages': 'Imazhet e Furnizimit me Ujë',
    'inspection.drainage': 'Kullimi',
    'inspection.drainageImages': 'Imazhet e Kullimit',
    'inspection.fixtures': 'Pajisjet',
    'inspection.fixturesImages': 'Imazhet e Pajisjeve',
    'inspection.plumbingNotes': 'Shënimet e Ujësjellësit',
    'inspection.heatingSystem': 'Sistemi i Ngrohjes',
    'inspection.heatingSystemImages': 'Imazhet e Sistemit të Ngrohjes',
    'inspection.coolingSystem': 'Sistemi i Ftohjes',
    'inspection.coolingSystemImages': 'Imazhet e Sistemit të Ftohjes',
    'inspection.ventilation': 'Ventilimi',
    'inspection.ventilationImages': 'Imazhet e Ventilimit',
    'inspection.hvacNotes': 'Shënimet HVAC',
    'inspection.smokeDetectors': 'Detektorët e Tymit',
    'inspection.smokeDetectorsImages': 'Imazhet e Detektorëve të Tymit',
    'inspection.carbonMonoxide': 'Detektorët e Monoksidit të Karbonit',
    'inspection.carbonMonoxideImages': 'Imazhet e Detektorëve të Monoksidit të Karbonit',
    'inspection.fireExtinguisher': 'Shuarësi i Zjarrit',
    'inspection.fireExtinguisherImages': 'Imazhet e Shuarësit të Zjarrit',
    'inspection.safetyNotes': 'Shënimet e Sigurisë',
    
    // Inspection Options
    'inspection.none': 'Asnjë',
    'inspection.excellent': 'I Shkëlqyer',
    'inspection.good': 'I Mirë',
    'inspection.fair': 'I Pranueshëm',
    'inspection.poor': 'I Dobët',
    'inspection.needsReplacement': 'Nevojitet Zëvendësim',
    'inspection.needsRepair': 'Nevojitet Riparim',
    'inspection.needsUpgrade': 'Nevojitet Përmirësim',
    'inspection.presentWorking': 'I Pranueshëm dhe Punon',
    'inspection.presentNeedsBattery': 'I Pranueshëm - Nevojitet Bateri',
    'inspection.missing': 'Mungon',
    'inspection.notTested': 'Nuk është Testuar',
    'inspection.presentCurrent': 'I Pranueshëm dhe Aktual',
    'inspection.presentExpired': 'I Pranueshëm - I Skaduar',
    
    // Placeholders 
    'inspection.enterField': 'Shkruani {{field}}...',
    
    // Inspection Completion Modal
    'inspectionCompletion.title': 'Përfundo Inspektimin',
    'inspectionCompletion.propertyDetails': 'Detajet e Pronës',
    'inspectionCompletion.peopleInvolved': 'Njerëzit e Përfshirë',
    'inspectionCompletion.inspectionSummary': 'Përmbledhja e Inspektimit',
    'inspectionCompletion.summary': 'Përmbledhja',
    'inspectionCompletion.summaryPlaceholder': 'Shkruani përmbledhjen e inspektimit...',
    'inspectionCompletion.previous': 'Mëparshëm',
    'inspectionCompletion.next': 'Tjetër',
    'inspectionCompletion.cancel': 'Anulo',
    'inspectionCompletion.completeInspection': 'Përfundo Inspektimin',
    'inspectionCompletion.step': 'Hapi {{current}} nga {{total}}',
    'inspectionCompletion.complete': '{{percentage}}% i Përfunduar',
    'inspectionCompletion.validationError': 'Gabim Validimi',
    'inspectionCompletion.enterSummaryFirst': 'Ju lutemi shkruani përmbledhjen e inspektimit para se të vazhdoni',
    'inspectionCompletion.completeRequiredFields': 'Ju lutemi plotësoni fushat e kërkuara: {{fields}}',
    'inspectionCompletion.completeRequiredFieldsBeforeSubmit': 'Ju lutemi plotësoni fushat e kërkuara para se të dorëzoni:\n\n{{fields}}',
    'inspectionCompletion.completeSummaryBeforeSubmit': 'Ju lutemi plotësoni përmbledhjen e inspektimit para se të dorëzoni',
    'inspectionCompletion.success': 'Sukses',
    'inspectionCompletion.completedSuccessfully': 'Inspektimi u përfundua dhe raporti u gjenerua me sukses!',
    'inspectionCompletion.failedToComplete': 'Dështoi përfundimi i inspektimit',
    'inspectionCompletion.property': 'Prona',
    'inspectionCompletion.address': 'Adresa',
    'inspectionCompletion.type': 'Lloji',
    'inspectionCompletion.size': 'Madhësia',
    'inspectionCompletion.client': 'Klienti',
    'inspectionCompletion.agent': 'Agjenti',
    'inspectionCompletion.name': 'Emri',
    'inspectionCompletion.email': 'Email',
    'inspectionCompletion.phone': 'Telefoni',
    'inspectionCompletion.inspection': 'Inspektimi',
    'inspectionCompletion.addImage': 'Shto Imazh',
    'inspectionCompletion.selectImageSource': 'Zgjidh Burimin e Imazhit',
    'inspectionCompletion.chooseImageSource': 'Zgjidh si dëshiron të shtosh një imazh',
    'inspectionCompletion.camera': 'Kamera',
    'inspectionCompletion.gallery': 'Galeria',
    'inspectionCompletion.cameraPermissionDenied': 'Leja e kamerës është e nevojshme për të marrë foto',
    
    // Inspection
    'inspection.inspection': 'Inspektimi',
    
    // Signature
    'signature.title': 'Nënshkrimet',
    'signature.signatures': 'Nënshkrimet',
    'signature.agentSignature': 'Nënshkrimi i Agjentit',
    'signature.clientSignature': 'Nënshkrimi i Klientit',
    'signature.agentName': 'Agjent: {{name}}',
    'signature.clientName': 'Klient: {{name}}',
    'signature.agent': 'Agjent',
    'signature.client': 'Klient',
    'signature.note': 'Të dy nënshkrimet janë të nevojshëm për të gjeneruar raportin',
    'signature.missingSignatures': 'Ju lutemi plotësoni nënshkrimet e mëposhtme: {{signatures}}',
    'signature.captured': 'Nënshkrimi u Kap',
    'signature.signHere': 'Nënshkruani këtu',
    'signature.clear': 'Pastro',
    'signature.save': 'Ruaj',
    'signature.processing': 'Duke përpunuar...',
  },
  de: {
    // Common
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.add': 'Hinzufügen',
    'common.loading': 'Lädt...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.confirm': 'Bestätigen',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.filter': 'Filter',
    'common.view': 'Anzeigen',
    'common.deleting': 'Löschen...',
    // Images
    'images.noImages': 'Keine Bilder',
    'images.notSpecified': 'Nicht angegeben',
    'images.propertyId': 'Immobilien-ID: {{id}}',
    'images.clientId': 'Kunden-ID: {{id}}',
    'images.agentId': 'Agent-ID: {{id}}',
    'images.propertyAddress': 'Immobilienadresse',
    'images.clientName': 'Kundenname',
    'images.agentName': 'Agentenname',
    
    // Network
    'network.online': 'Online',
    'network.offline': 'Offline',
    'network.pendingSync': '{{count}} ausstehende Synchronisation',
    'network.syncing': 'Synchronisiere...',
    'network.sync': 'Synchronisieren',
    'network.lastSync': 'Letzte Synchronisation: {{time}}',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.reports': 'Berichte',
    'nav.schedules': 'Termine',
    'nav.profile': 'Profil',
    'nav.settings': 'Einstellungen',
    
    // Settings
    'settings.title': 'Einstellungen',
    'settings.subtitle': 'Verwalten Sie Ihre App-Einstellungen',
    'settings.profile': 'Profil',
    'settings.appPreferences': 'App-Einstellungen',
    'settings.dataManagement': 'Datenverwaltung',
    'settings.supportLegal': 'Support & Rechtliches',
    'settings.account': 'Konto',
    'settings.language': 'Sprache',
    'settings.languageSubtitle': 'Wählen Sie Ihre bevorzugte Sprache',
    'settings.notifications': 'Benachrichtigungen',
    'settings.notificationsSubtitle': 'Erhalten Sie Inspektionserinnerungen und Updates',
    'settings.pushNotifications': 'Push-Benachrichtigungen',
    'settings.pushNotificationsSubtitle': 'Erhalten Sie Inspektionserinnerungen und Updates',
    'settings.emailNotifications': 'Email-Benachrichtigungen',
    'settings.emailNotificationsSubtitle': 'Erhalten Sie Inspektionserinnerungen und Updates via Email',
    'settings.autoSync': 'Auto-Sync',
    'settings.autoSyncSubtitle': 'Automatisch synchronisieren, wenn online',
    'settings.darkMode': 'Dunkler Modus',
    'settings.darkModeSubtitle': 'Zum dunklen Design wechseln',
    'settings.biometric': 'Biometrische Anmeldung',
    'settings.biometricSubtitle': 'Fingerabdruck oder Gesichtserkennung verwenden',
    'settings.biometricLogin': 'Biometrische Anmeldung',
    'settings.biometricLoginSubtitle': 'Fingerabdruck oder Gesichtserkennung verwenden',
    'settings.exportData': 'Daten exportieren',
    'settings.exportDataSubtitle': 'Alle Ihre Inspektionsdaten herunterladen',
    'settings.storageUsage': 'Speichernutzung',
    'settings.storageUsageSubtitle': '2,3 GB von 5 GB verfügbar verwendet',
    'settings.clearCache': 'Cache leeren',
    'settings.clearCacheSubtitle': 'Speicherplatz freigeben',
    'settings.helpSupport': 'Hilfe & Support',
    'settings.helpSupportSubtitle': 'Hilfe zur App erhalten',
    'settings.about': 'Über',
    'settings.aboutSubtitle': 'Version 1.0.0',
    'settings.privacyPolicy': 'Datenschutzrichtlinie',
    'settings.privacyPolicySubtitle': 'Unsere Datenschutzrichtlinie lesen',
    'settings.termsOfService': 'Nutzungsbedingungen',
    'settings.termsOfServiceSubtitle': 'Unsere Nutzungsbedingungen lesen',
    'settings.logout': 'Abmelden',
    'settings.logoutSubtitle': 'Von Ihrem Konto abmelden',
    'settings.appName': 'Immobilien-Inspektions-App',
    'settings.appVersion': 'Version 1.0.0 • Hergestellt von Vorbulla',
    
    // Language names
    'language.english': 'Englisch',
    'language.albanian': 'Albanisch',
    'language.german': 'Deutsch',
    
    // Alerts
    'alert.logout': 'Abmelden',
    'alert.logoutMessage': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
    'alert.exportData': 'Daten exportieren',
    'alert.exportDataMessage': 'Dies exportiert alle Ihre Inspektionsdaten in eine CSV-Datei.',
    'alert.exportSuccess': 'Daten erfolgreich exportiert!',
    'alert.clearCache': 'Cache leeren',
    'alert.clearCacheMessage': 'Dies löscht alle gecachten Daten und gibt Speicherplatz frei.',
    'alert.clearCacheSuccess': 'Cache erfolgreich geleert!',
    'alert.about': 'Über',
    'alert.aboutMessage': 'Immobilien-Inspektions-App v1.0.0\nMit React Native erstellt',
    'alert.storage': 'Speicher',
    'alert.storageMessage': 'Speichernutzung verwalten',
    
    // Login
    'login.title': 'Immobilien-Inspektor',
    'login.subtitle': 'Melden Sie sich an, um Ihre Inspektionen zu starten',
    'login.email': 'E-Mail',
    'login.emailPlaceholder': 'Geben Sie Ihre E-Mail ein',
    'login.password': 'Passwort',
    'login.passwordPlaceholder': 'Geben Sie Ihr Passwort ein',
    'login.signIn': 'Anmelden',
    'login.error': 'Fehler',
    'login.fillFields': 'Bitte füllen Sie alle Felder aus',
    'login.failed': 'Anmeldung fehlgeschlagen',
    'login.tryAgain': 'Anmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Verwalten Sie Ihre Inspektionen',
    'dashboard.searchPlaceholder': 'Inspektionen suchen...',
    'dashboard.moveInInspection': 'Einzugsinspektion',
    'dashboard.moveOutInspection': 'Auszugsinspektion',
    'dashboard.periodicInspection': 'Periodische Inspektion',
    'dashboard.maintenanceInspection': 'Wartungsinspektion',
    'dashboard.today': 'Heute',
    'dashboard.upcoming': 'Bevorstehend',
    'dashboard.inProgress': 'In Bearbeitung',
    'dashboard.completed': 'Abgeschlossen',
    'dashboard.cancelled': 'Abgebrochen',
    'dashboard.noInspections': 'Keine Inspektionen gefunden',
    'dashboard.noInspectionsMessage': 'Beginnen Sie mit Ihrer ersten Inspektion',
    'dashboard.goodMorning': 'Guten Morgen,',
    'dashboard.all': 'Alle',
    'dashboard.tryAdjustingSearch': 'Versuchen Sie, Ihre Suche anzupassen',
    'dashboard.overview': 'Übersicht',
    'dashboard.totalReports': 'Gesamtberichte',
    'dashboard.draftReports': 'Entwurfsberichte',
    'dashboard.recentReports': 'Aktuelle Berichte',
    'dashboard.viewAll': 'Alle anzeigen',
    'dashboard.filterInspections': 'Inspektionen filtern',
    'dashboard.noReports': 'Noch keine Berichte erstellt',
    'dashboard.noReportsMessage': 'Erstellen Sie Ihren ersten Bericht',
    'dashboard.scheduleInspection': 'Inspektion planen',
    // Reports
    'reports.subtitle': 'Inspektionsberichte verwalten',
    'reports.searchPlaceholder': 'Berichte suchen...',
    'reports.allTypes': 'Alle Typen',
    'reports.noReports': 'Noch keine Berichte erstellt',
    'reports.noReportsMessage': 'Erstellen Sie Ihren ersten Bericht',
    'reports.reportDetails': 'Berichtdetails',
    'reports.reportInformation': 'Berichtsinformationen',
    'reports.propertyDetails': 'Immobiliendetails',
    'reports.peopleInvolved': 'Beteiligte Personen',
    'reports.inspectionDetails': 'Inspektionsdetails',
    'reports.inspectionImages': 'Inspektionsbilder',
    'reports.title': 'Titel',
    'reports.type': 'Typ',
    'reports.status': 'Status',
    'reports.date': 'Datum',
    'reports.property': 'Immobilie',
    'reports.client': 'Kunde',
    'reports.agent': 'Mitarbeiter',
    'reports.email': 'E-Mail',
    'reports.sendReportViaEmail': 'Bericht per E-Mail senden',
    'reports.sendEmailConfirmation': 'Sind Sie sicher, dass Sie "{{title}}" per E-Mail senden möchten?',
    'reports.sendEmail': 'E-Mail senden',
    'reports.reportCreatedSuccessfully': 'Bericht erfolgreich erstellt',
    'reports.reportGeneratedMessage': 'Ihr Inspektionsbericht wurde erfolgreich generiert und gespeichert.',
    'reports.failedToRefreshList': 'Aktualisierung der Berichtsliste fehlgeschlagen. Bitte manuell überprüfen.',
    'reports.reportsRefreshed': 'Berichte aktualisiert',
    'reports.reportsListUpdated': 'Berichtsliste wurde erfolgreich aktualisiert.',
    'reports.refreshError': 'Aktualisierungsfehler',
    'reports.failedToRefresh': 'Aktualisierung der Berichte fehlgeschlagen. Bitte versuchen Sie es erneut.',
    'reports.reportDataNotFound': 'Berichtsdaten nicht gefunden',
    'reports.noEmailAvailable': 'Keine E-Mail verfügbar',
    'reports.failedToLoadEmailData': 'Laden der E-Mail-Daten fehlgeschlagen',
    'reports.emailSentSuccessfully': 'E-Mail erfolgreich gesendet',
    'reports.emailSentMessage': 'Ihr Bericht wurde per E-Mail an den Mitarbeiter und Kunden gesendet.',
    'reports.failedToSendEmails': 'E-Mail-Versand fehlgeschlagen',
    'reports.failedToSendEmailsWithConnection': 'E-Mail-Versand fehlgeschlagen. Bitte überprüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
    'reports.reportNotFound': 'Bericht nicht gefunden',
    'reports.loadingReportDetails': 'Berichtsdetails werden geladen...',
    'reports.securityDeposit': 'Kaution',
    'reports.amount': 'Betrag:',
    'reports.paymentMethod': 'Zahlungsmethode:',
    'reports.notes': 'Notizen:',
    'reports.noInspectionDataAvailable': 'Keine Inspektionsdaten verfügbar',
    'reports.contentType': 'Inhaltstyp:',
    'reports.contentExistsNoData': 'Inhalt vorhanden, aber keine Inspektionsdaten',
    'reports.noContentFound': 'Kein Inhalt gefunden',
    'reports.contentKeys': 'Inhaltsschlüssel:',
    'reports.loadFailed': 'Laden fehlgeschlagen',
    'reports.invalidUri': 'Ungültige URI',
    'reports.emailRecipients': 'E-Mail-Empfänger',
    'reports.agentEmailLabel': 'Agent E-Mail',
    'reports.clientEmailLabel': 'Kunden E-Mail',
    'reports.emailWarningMessage': 'Diese Aktion sendet den Bericht an beide Empfänger. Bitte stellen Sie sicher, dass die E-Mail-Adressen korrekt sind.',
    'reports.processing': 'Wird verarbeitet...',
    'reports.confirmAction': 'Aktion bestätigen',
    'reports.confirmActionSubtitle': 'Sind Sie sicher, dass Sie fortfahren möchten?',
    // Common actions
    'common.complete': 'Abschließen',
    'common.completing': 'Wird abgeschlossen...',
    'common.cancelling': 'Wird abgebrochen...',
    
    // Schedules
    'schedules.title': 'Termine',
    'schedules.subtitle': 'Inspektionstermine verwalten',
    'schedules.loadingInspections': 'Inspektionen werden geladen...',
    'schedules.noInspections': 'Keine Inspektionen zugewiesen',
    'schedules.noInspectionsMessage': 'Sie haben keine Inspektionen für dieses Datum geplant',
    'schedules.cancelInspection': 'Inspektion abbrechen',
    'schedules.cancelInspectionMessage': 'Sind Sie sicher, dass Sie diese Inspektion abbrechen möchten?',
    'schedules.markCompleted': 'Als abgeschlossen markieren',
    'schedules.markCompletedMessage': 'Sind Sie sicher, dass Sie diese Inspektion als abgeschlossen markieren möchten?',
    'schedules.inspectionCancelled': 'Inspektion erfolgreich abgebrochen',
    'schedules.inspectionCompleted': 'Inspektion erfolgreich als abgeschlossen markiert',
    'schedules.failedToCancel': 'Fehler beim Abbrechen der Inspektion',
    'schedules.failedToComplete': 'Fehler beim Markieren als abgeschlossen',
    'schedules.failedToLoad': 'Fehler beim Laden der Inspektionen',
    'schedules.failedToLoadDetails': 'Fehler beim Laden der Inspektionsdetails',
    'schedules.client': 'Kunde',
    'schedules.agent': 'Mitarbeiter',
    'schedules.property': 'Immobilie',
    'schedules.inspection': 'Inspektion',
    'schedules.overdue': 'Überfällig',
    'schedules.scheduled': 'Geplant',
    'schedules.inProgress': 'In Bearbeitung',
    'schedules.pending': 'Ausstehend',
    'schedules.completed': 'Abgeschlossen',
    'schedules.cancelled': 'Abgebrochen',
    
    // Calendar
    'calendar.january': 'Januar',
    'calendar.february': 'Februar',
    'calendar.march': 'März',
    'calendar.april': 'April',
    'calendar.may': 'Mai',
    'calendar.june': 'Juni',
    'calendar.july': 'Juli',
    'calendar.august': 'August',
    'calendar.september': 'September',
    'calendar.october': 'Oktober',
    'calendar.november': 'November',
    'calendar.december': 'Dezember',
    'calendar.sunday': 'So',
    'calendar.monday': 'Mo',
    'calendar.tuesday': 'Di',
    'calendar.wednesday': 'Mi',
    'calendar.thursday': 'Do',
    'calendar.friday': 'Fr',
    'calendar.saturday': 'Sa',
    
    // Profile Screen
    'profile.inspections': 'Inspektionen',
    'profile.properties': 'Immobilien',
    'profile.reports': 'Berichte',
    'profile.changePassword': 'Passwort ändern',
    'profile.changePasswordSubtitle': 'Ihr Kontopasswort aktualisieren',
    'profile.passwordChanged': 'Passwort geändert',
    'profile.passwordChangedMessage': 'Ihr Passwort wurde erfolgreich geändert. Sie werden aus Sicherheitsgründen abgemeldet.',
    'profile.ok': 'OK',
    
    // Change Password Modal
    'password.title': 'Passwort ändern',
    'password.currentPassword': 'Aktuelles Passwort',
    'password.newPassword': 'Neues Passwort',
    'password.confirmPassword': 'Neues Passwort bestätigen',
    'password.currentPasswordPlaceholder': 'Geben Sie Ihr aktuelles Passwort ein',
    'password.newPasswordPlaceholder': 'Geben Sie Ihr neues Passwort ein',
    'password.confirmPasswordPlaceholder': 'Bestätigen Sie Ihr neues Passwort',
    'password.currentPasswordRequired': 'Aktuelles Passwort ist erforderlich',
    'password.newPasswordRequired': 'Neues Passwort ist erforderlich',
    'password.confirmPasswordRequired': 'Bitte bestätigen Sie Ihr neues Passwort',
    'password.passwordsDoNotMatch': 'Passwörter stimmen nicht überein',
    'password.passwordChangedSuccessfully': 'Passwort erfolgreich geändert',
    'password.failedToChangePassword': 'Passwortänderung fehlgeschlagen',
    'password.unexpectedError': 'Ein unerwarteter Fehler ist aufgetreten',
    'password.weak': 'Schwach',
    'password.medium': 'Mittel',
    'password.strong': 'Stark',
    'password.requirements': 'Passwort-Anforderungen:',
    'password.securityNote': 'Aus Sicherheitsgründen werden Sie nach der Passwortänderung abgemeldet. Bitte melden Sie sich mit Ihrem neuen Passwort an.',
    'password.changePassword': 'Passwort ändern',
    
    // Generate Report Modal
    'report.generate': 'Bericht erstellen',
    'report.selectProperty': 'Immobilie auswählen',
    'report.selectAgentClient': 'Mitarbeiter & Kunde auswählen',
    'report.reportDetails': 'Berichtdetails',
    'report.step': 'Schritt {{current}} von {{total}}',
    'report.complete': '{{percentage}}% Abgeschlossen',
    'report.previous': 'Zurück',
    'report.next': 'Weiter',
    'report.cancel': 'Abbrechen',
    'report.generateReport': 'Bericht erstellen',
    'report.loadingProperties': 'Immobilien werden geladen...',
    'report.loadingAgents': 'Mitarbeiter werden geladen...',
    'report.loadingClients': 'Kunden werden geladen...',
    'report.noProperties': 'Keine Immobilien gefunden',
    'report.noPropertiesMessage': 'Sie müssen zuerst Immobilien hinzufügen, bevor Sie Berichte erstellen können. Bitte gehen Sie zum Immobilien-Bereich, um einige Immobilien hinzuzufügen.',
    'report.goToProperties': 'Zu Immobilien gehen',
    'report.addProperties': 'Immobilien hinzufügen',
    'report.addPropertiesMessage': 'Bitte gehen Sie zum Immobilien-Bereich in der Haupt-App, um zuerst Immobilien hinzuzufügen.',
    'report.selectAgent': 'Mitarbeiter auswählen *',
    'report.selectClient': 'Kunde auswählen *',
    'report.currentAgent': 'Aktueller Mitarbeiter',
    'report.noAgents': 'Keine Mitarbeiter gefunden',
    'report.noAgentsMessage': 'Keine Mitarbeiter verfügbar. Bitte kontaktieren Sie Ihren Administrator.',
    'report.noClients': 'Keine Kunden gefunden',
    'report.noClientsMessage': 'Keine Kunden verfügbar. Bitte fügen Sie zuerst Kunden hinzu.',
    'report.reportTitle': 'Berichtstitel *',
    'report.reportTitlePlaceholder': 'Berichtstitel eingeben...',
    'report.database': 'Datenbank: {{name}}',
    'report.owner': 'Eigentümer: {{name}}',
    'report.you': ' (Sie)',
    'report.validationError': 'Validierungsfehler',
    'report.selectPropertyFirst': 'Bitte wählen Sie zuerst eine Immobilie aus',
    'report.selectAgentClientFirst': 'Bitte wählen Sie sowohl einen Mitarbeiter als auch einen Kunden aus',
    'report.enterTitleFirst': 'Bitte geben Sie zuerst einen Berichtstitel ein',
    'report.completeRequiredFields': 'Bitte füllen Sie alle erforderlichen Felder aus, bevor Sie den Bericht erstellen',
    'report.generatedSuccessfully': 'Bericht erfolgreich erstellt!',
    'report.failedToGenerate': 'Berichterstellung fehlgeschlagen',
    'report.failedToLoadProperties': 'Laden der Immobilien fehlgeschlagen: {{error}}',
    'report.failedToLoadAgents': 'Laden der Mitarbeiter fehlgeschlagen: {{error}}',
    'report.failedToLoadClients': 'Laden der Kunden fehlgeschlagen: {{error}}',
    'report.errorRendering': 'Fehler beim Rendern des Schrittinhalts',
    'report.errorRenderingModal': 'Ein Fehler ist beim Rendern des Modals aufgetreten',
    'report.errorProceeding': 'Ein Fehler ist beim Fortfahren zum nächsten Schritt aufgetreten: {{error}}',
    'report.propertyNotFoundError': 'Die ausgewählte Immobilie konnte nicht gefunden werden. Bitte versuchen Sie, eine andere Immobilie auszuwählen oder kontaktieren Sie den Support.',
    'report.clientNotFoundError': 'Der ausgewählte Kunde konnte nicht gefunden werden. Bitte versuchen Sie, einen anderen Kunden auszuwählen oder kontaktieren Sie den Support.',
    'report.missingFieldsError': 'Bitte stellen Sie sicher, dass alle erforderlichen Felder korrekt ausgefüllt sind.',
    
    // Inspection Areas
    'inspection.exterior': 'Außenbereich',
    'inspection.interior': 'Innenbereich',
    'inspection.electrical': 'Elektrik',
    'inspection.plumbing': 'Sanitär',
    'inspection.hvac': 'HVAC',
    'inspection.safety': 'Sicherheit',
    'inspection.exteriorInspection': 'Außeninspektion',
    'inspection.interiorInspection': 'Inneninspektion',
    'inspection.electricalInspection': 'Elektroinspektion',
    'inspection.plumbingInspection': 'Sanitärinspektion',
    'inspection.hvacInspection': 'HVAC-Inspektion',
    'inspection.safetyInspection': 'Sicherheitsinspektion',
    
    // Inspection Fields
    'inspection.roofCondition': 'Dachzustand',
    'inspection.roofImages': 'Dachbilder',
    'inspection.sidingCondition': 'Fassadenzustand',
    'inspection.sidingImages': 'Fassadenbilder',
    'inspection.windowsDoors': 'Fenster & Türen',
    'inspection.windowsImages': 'Fensterbilder',
    'inspection.foundation': 'Fundament',
    'inspection.foundationImages': 'Fundamentbilder',
    'inspection.exteriorNotes': 'Außennotizen',
    'inspection.wallsCondition': 'Wandzustand',
    'inspection.wallsImages': 'Wandbilder',
    'inspection.floorsCondition': 'Bodenzustand',
    'inspection.floorsImages': 'Bodenbilder',
    'inspection.ceilingsCondition': 'Deckenzustand',
    'inspection.ceilingsImages': 'Deckenbilder',
    'inspection.interiorNotes': 'Innennotizen',
    'inspection.electricalSystem': 'Elektroanlage',
    'inspection.electricalSystemImages': 'Elektroanlagenbilder',
    'inspection.outletsSwitches': 'Steckdosen & Schalter',
    'inspection.outletsImages': 'Steckdosenbilder',
    'inspection.lighting': 'Beleuchtung',
    'inspection.lightingImages': 'Beleuchtungsbilder',
    'inspection.electricalNotes': 'Elektronotizen',
    'inspection.waterSupply': 'Wasserversorgung',
    'inspection.waterSupplyImages': 'Wasserversorgungsbilder',
    'inspection.drainage': 'Entwässerung',
    'inspection.drainageImages': 'Entwässerungsbilder',
    'inspection.fixtures': 'Armaturen',
    'inspection.fixturesImages': 'Armaturenbilder',
    'inspection.plumbingNotes': 'Sanitärnotizen',
    'inspection.heatingSystem': 'Heizsystem',
    'inspection.heatingSystemImages': 'Heizsystembilder',
    'inspection.coolingSystem': 'Kühlsystem',
    'inspection.coolingSystemImages': 'Kühlsystembilder',
    'inspection.ventilation': 'Belüftung',
    'inspection.ventilationImages': 'Belüftungsbilder',
    'inspection.hvacNotes': 'HVAC-Notizen',
    'inspection.smokeDetectors': 'Rauchmelder',
    'inspection.smokeDetectorsImages': 'Rauchmelderbilder',
    'inspection.carbonMonoxide': 'Kohlenmonoxid-Melder',
    'inspection.carbonMonoxideImages': 'Kohlenmonoxid-Melderbilder',
    'inspection.fireExtinguisher': 'Feuerlöscher',
    'inspection.fireExtinguisherImages': 'Feuerlöscherbilder',
    'inspection.safetyNotes': 'Sicherheitsnotizen',
    
    // Inspection Options
    'inspection.none': 'Keine',
    'inspection.excellent': 'Ausgezeichnet',
    'inspection.good': 'Gut',
    'inspection.fair': 'Befriedigend',
    'inspection.poor': 'Schlecht',
    'inspection.needsReplacement': 'Ersetzung erforderlich',
    'inspection.needsRepair': 'Reparatur erforderlich',
    'inspection.needsUpgrade': 'Upgrade erforderlich',
    'inspection.presentWorking': 'Vorhanden & Funktionsfähig',
    'inspection.presentNeedsBattery': 'Vorhanden - Batterie erforderlich',
    'inspection.missing': 'Fehlt',
    'inspection.notTested': 'Nicht getestet',
    'inspection.presentCurrent': 'Vorhanden & Aktuell',
    'inspection.presentExpired': 'Vorhanden - Abgelaufen',
    
    // Placeholders
    'inspection.enterField': '{{field}} eingeben...',
    
    // Inspection Completion Modal
    'inspectionCompletion.title': 'Inspektion Abschließen',
    'inspectionCompletion.propertyDetails': 'Immobiliendetails',
    'inspectionCompletion.peopleInvolved': 'Beteiligte Personen',
    'inspectionCompletion.inspectionSummary': 'Inspektionszusammenfassung',
    'inspectionCompletion.summary': 'Zusammenfassung',
    'inspectionCompletion.summaryPlaceholder': 'Inspektionszusammenfassung eingeben...',
    'inspectionCompletion.previous': 'Zurück',
    'inspectionCompletion.next': 'Weiter',
    'inspectionCompletion.cancel': 'Abbrechen',
    'inspectionCompletion.completeInspection': 'Inspektion Abschließen',
    'inspectionCompletion.step': 'Schritt {{current}} von {{total}}',
    'inspectionCompletion.complete': '{{percentage}}% Abgeschlossen',
    'inspectionCompletion.validationError': 'Validierungsfehler',
    'inspectionCompletion.enterSummaryFirst': 'Bitte geben Sie eine Inspektionszusammenfassung ein, bevor Sie fortfahren',
    'inspectionCompletion.completeRequiredFields': 'Bitte vervollständigen Sie die folgenden erforderlichen Felder: {{fields}}',
    'inspectionCompletion.completeRequiredFieldsBeforeSubmit': 'Bitte vervollständigen Sie die folgenden erforderlichen Felder vor der Einreichung:\n\n{{fields}}',
    'inspectionCompletion.completeSummaryBeforeSubmit': 'Bitte vervollständigen Sie die Inspektionszusammenfassung vor der Einreichung',
    'inspectionCompletion.success': 'Erfolg',
    'inspectionCompletion.completedSuccessfully': 'Inspektion erfolgreich abgeschlossen und Bericht generiert!',
    'inspectionCompletion.failedToComplete': 'Fehler beim Abschließen der Inspektion',
    'inspectionCompletion.property': 'Immobilie',
    'inspectionCompletion.address': 'Adresse',
    'inspectionCompletion.type': 'Typ',
    'inspectionCompletion.size': 'Größe',
    'inspectionCompletion.client': 'Kunde',
    'inspectionCompletion.agent': 'Mitarbeiter',
    'inspectionCompletion.name': 'Name',
    'inspectionCompletion.email': 'E-Mail',
    'inspectionCompletion.phone': 'Telefon',
    'inspectionCompletion.inspection': 'Inspektion',
    'inspectionCompletion.addImage': 'Bild Hinzufügen',
    'inspectionCompletion.selectImageSource': 'Bildquelle Auswählen',
    'inspectionCompletion.chooseImageSource': 'Wählen Sie aus, wie Sie ein Bild hinzufügen möchten',
    'inspectionCompletion.camera': 'Kamera',
    'inspectionCompletion.gallery': 'Galerie',
    'inspectionCompletion.cameraPermissionDenied': 'Kameraberechtigung ist erforderlich, um Fotos aufzunehmen',
    
    // Inspection
    'inspection.inspection': 'Inspektion',
    
    // Signature
    'signature.title': 'Unterschriften',
    'signature.signatures': 'Unterschriften',
    'signature.agentSignature': 'Mitarbeiter-Unterschrift',
    'signature.clientSignature': 'Kunden-Unterschrift',
    'signature.agentName': 'Mitarbeiter: {{name}}',
    'signature.clientName': 'Kunde: {{name}}',
    'signature.agent': 'Mitarbeiter',
    'signature.client': 'Kunde',
    'signature.note': 'Beide Unterschriften sind erforderlich, um den Bericht zu generieren',
    'signature.missingSignatures': 'Bitte vervollständigen Sie die folgenden Unterschriften: {{signatures}}',
    'signature.captured': 'Unterschrift Erfasst',
    'signature.signHere': 'Hier unterschreiben',
    'signature.clear': 'Löschen',
    'signature.save': 'Speichern',
    'signature.processing': 'Wird verarbeitet...',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load saved language preference on app start
  useEffect(() => {
    loadLanguagePreference();
  }, []);

  const loadLanguagePreference = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem('language');
      if (savedLanguage && ['en', 'alb', 'de'].includes(savedLanguage)) {
        setLanguageState(savedLanguage as Language);
      }
    } catch (error) {
      console.error('Error loading language preference:', error);
    }
  };

  const saveLanguagePreference = async (lang: Language) => {
    try {
      await AsyncStorage.setItem('language', lang);
    } catch (error) {
      console.error('Error saving language preference:', error);
    }
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    saveLanguagePreference(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key as keyof typeof translations[typeof language]] || key;
    
    // Handle interpolation
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(new RegExp(`{{${param}}}`, 'g'), String(params[param]));
      });
    }
    
    return translation;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
