import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'en' | 'de'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation object
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.properties': 'Properties',
    'nav.clients': 'Clients',
    'nav.agents': 'Agents',
    'nav.scheduling': 'Scheduling',
    'nav.reports': 'Reports',
    'nav.notifications': 'Notifications',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Property inspection management overview',
    'dashboard.totalProperties': 'Total Properties',
    'dashboard.activeInspections': 'Active Appointments',
    'dashboard.completedInspections': 'Completed Appointments',
    'dashboard.totalClients': 'Total Clients',
    'dashboard.availableAgents': 'Agents',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.upcomingInspections': 'Upcoming Appointments',
    'dashboard.noProperties': 'No properties yet',
    'dashboard.propertiesPortfolio': 'Properties in your portfolio',
    'dashboard.noClients': 'No clients yet',
    'dashboard.activeClients': 'Active client relationships',
    'dashboard.noAgents': 'No agents yet',
    'dashboard.agentsReady': 'Agents ready for inspections',
    'dashboard.noPending': 'No pending inspections',
    'dashboard.scheduledInspections': 'Appointments',
    'dashboard.inspectionOverview': 'Inspection Overview',
    'dashboard.monthlyOverview': 'Monthly completed vs scheduled inspections',
    'dashboard.noInspectionData': 'No inspection data available',
    'dashboard.chartWillAppear': 'Chart will appear when inspection data is available',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.addProperty': 'Add Property',
    'dashboard.addClient': 'Add Client',
    'dashboard.scheduleInspection': 'Schedule Appointments',
    'dashboard.addAgent': 'Add Agent',
    'dashboard.recentInspections': 'Recent Inspections',
    'dashboard.latestActivities': 'Latest inspection activities',
    'dashboard.noUpcomingInspections': 'No upcoming inspections',
    'dashboard.upcomingActivitiesWillAppear': 'Upcoming activities will appear here',
    'dashboard.status.completed': 'completed',
    'dashboard.status.upcoming': 'upcoming',
    'dashboard.viewAll': 'View All',
    'dashboard.appointment': 'Appointment',
    'dashboard.client': 'Client',
    'dashboard.agent': 'Agent',
    'dashboard.date': 'Date',
    'dashboard.status': 'Status',
    'dashboard.noRecentInspections': 'No recent inspections',
    'dashboard.recentActivitiesWillAppear': 'Recent inspection activities will appear here',
    
    // Properties
    'properties.title': 'Properties',
    'properties.subtitle': 'Manage your property portfolio',
    'properties.addProperty': 'Add Property',
    'properties.searchPlaceholder': 'Search properties...',
    'properties.filter': 'Filter',
    'properties.property': 'Property',
    'properties.address': 'Address',
    'properties.details': 'Details',
    'properties.rentPrice': 'Rent Price',
    'properties.status': 'Status',
    'properties.actions': 'Actions',
    'properties.view': 'View',
    'properties.edit': 'Edit',
    'properties.delete': 'Delete',
    'properties.noProperties': 'No properties added yet. Click \'Add Property\' to get started.',
    'properties.noResults': 'No properties found matching your search.',
    'properties.detail.propertyDetails': 'Property Details',
    'properties.detail.subtitle': 'View detailed information about this property',
    'properties.detail.summary': 'Summary',
    'properties.detail.address': 'Address',
    'properties.detail.totalUnits': 'Total Units',
    'properties.detail.manager': 'Manager',
    'properties.detail.hierarchicalStructure': 'Hierarchical Structure',
    'properties.detail.noStructure': 'No hierarchical structure defined for this property',
    'properties.detail.entrance': 'Entrance',
    'properties.detail.floor': 'Floor',
    'properties.detail.floors': 'floors',
    'properties.detail.unit': 'Unit',
    'properties.detail.units': 'units',
    'properties.detail.unitType.apartment': 'Apartment',
    'properties.detail.unitType.office': 'Office',
    'properties.detail.unitType.parking': 'Parking',
    'properties.detail.unitType.storage': 'Storage',
    'properties.detail.documentsContracts': 'Documents & Contracts',
    'properties.detail.noDocuments': 'No documents available',
    'properties.detail.documentType.contract': 'Contract',
    'properties.detail.documentType.document': 'Document',
    'properties.detail.documentType.other': 'Other',
    'properties.detail.view': 'View',
    'properties.detail.interventionHistory': 'Intervention History',
    'properties.detail.noInterventions': 'No interventions recorded',
    'properties.detail.performedBy': 'Performed by',
    'properties.detail.cost': 'Cost',
    'properties.detail.notFound': 'Property not found',
    'properties.detail.unitsTable': 'Units',
    'properties.detail.noUnits': 'No units added yet',
    'properties.detail.location': 'Location',
    'properties.detail.type': 'Type',
    'properties.detail.details': 'Details',
    'properties.detail.size': 'Size',
    'properties.detail.status': 'Status',
    'properties.detail.addUnitButton': 'Add Unit',
    'properties.detail.addUnit.title': 'Add Unit',
    'properties.detail.addUnit.subtitle': 'Create a new unit within this property',
    'properties.detail.addUnit.entranceName': 'Entrance Name or Number',
    'properties.detail.addUnit.entrancePlaceholder': 'Entrance A',
    'properties.detail.addUnit.floorNumber': 'Floor Number',
    'properties.detail.addUnit.floorPlaceholder': '1',
    'properties.detail.addUnit.unitNumber': 'Unit Number',
    'properties.detail.addUnit.validation': 'Please fill all required fields',
    'properties.detail.addUnit.success': 'Unit added successfully!',
    'properties.detail.addUnit.error': 'Failed to add unit',
    'properties.detail.addUnit.save': 'Save Unit',
    'properties.detail.addUnit.saving': 'Saving...',
    'properties.detail.addUnit.tenant': 'Tenant',
    'properties.detail.addUnit.notes': 'Notes',
    'properties.detail.addUnit.notesPlaceholder': 'Additional notes about this unit',
    'properties.detail.addDocumentButton': 'Add Document',
    'properties.detail.addDocument.title': 'Upload Document',
    'properties.detail.addDocument.subtitle': 'Upload a document or contract for this property',
    'properties.detail.addDocument.name': 'Document Name',
    'properties.detail.addDocument.namePlaceholder': 'e.g., Lease Agreement, Insurance Policy',
    'properties.detail.addDocument.type': 'Document Type',
    'properties.detail.addDocument.file': 'PDF File',
    'properties.detail.addDocument.filePlaceholder': 'Click to upload PDF document',
    'properties.detail.addDocument.fileHint': 'PDF files only, max 10MB',
    'properties.detail.addDocument.upload': 'Upload Document',
    'properties.detail.addDocument.uploading': 'Uploading...',
    'properties.detail.addDocument.success': 'Document uploaded successfully',
    'properties.detail.addDocument.errors.fillRequired': 'Please fill in all required fields',
    'properties.detail.addDocument.errors.uploadFailed': 'Failed to upload document',
    
    // Clients
    'clients.title': 'Clients',
    'clients.subtitle': 'Manage your client relationships',
    'clients.addClient': 'Add Client',
    'clients.searchPlaceholder': 'Search clients...',
    'clients.filter': 'Filter',
    'clients.client': 'Client',
    'clients.contact': 'Contact',
    'clients.address': 'Address',
    'clients.status': 'Status',
    'clients.actions': 'Actions',
    'clients.email': 'Email',
    'clients.call': 'Call',
    'clients.edit': 'Edit',
    'clients.delete': 'Delete',
    'clients.noClients': 'No clients added yet. Click \'Add Client\' to get started.',
    'clients.noResults': 'No clients found matching your search.',
    
    // Client Edit Modal
    'clients.editClient.title': 'Edit Client',
    'clients.editClient.subtitle': 'Update client information',
    'clients.editClient.basicInfo': 'Basic Information',
    'clients.editClient.firstName': 'First Name',
    'clients.editClient.firstNamePlaceholder': 'John',
    'clients.editClient.lastName': 'Last Name',
    'clients.editClient.lastNamePlaceholder': 'Doe',
    'clients.editClient.contactInfo': 'Contact Information',
    'clients.editClient.email': 'Email Address',
    'clients.editClient.emailPlaceholder': 'john.doe@example.com',
    'clients.editClient.phone': 'Phone Number',
    'clients.editClient.phonePlaceholder': '+41 44 123 45 67',
    'clients.editClient.addressInfo': 'Address Information',
    'clients.editClient.streetAddress': 'Street Address',
    'clients.editClient.streetPlaceholder': '123 Main Street',
    'clients.editClient.city': 'City',
    'clients.editClient.cityPlaceholder': 'New York',
    'clients.editClient.state': 'State/Province',
    'clients.editClient.statePlaceholder': 'NY',
    'clients.editClient.zipCode': 'ZIP/Postal Code',
    'clients.editClient.zipPlaceholder': '10001',
    'clients.editClient.country': 'Country',
    'clients.editClient.countryPlaceholder': 'United States',
    'clients.editClient.status': 'Client Status',
    'clients.editClient.statusActive': 'Active',
    'clients.editClient.statusInactive': 'Inactive',
    'clients.editClient.statusProspect': 'Prospect',
    'clients.editClient.additionalInfo': 'Additional Information',
    'clients.editClient.notes': 'Notes',
    'clients.editClient.notesPlaceholder': 'Add any additional notes about this client...',
    'clients.editClient.cancel': 'Cancel',
    'clients.editClient.update': 'Update Client',
    'clients.editClient.updating': 'Updating Client...',
    
    // Client Messages and Errors
    'clients.messages.updateSuccess': 'Client updated successfully!',
    'clients.errors.clientIdNotFound': 'Client ID not found',
    'clients.errors.fillRequiredFields': 'Please fill in all required fields',
    'clients.errors.validEmail': 'Please enter a valid email address',
    'clients.errors.validPhone': 'Please enter a valid phone number',
    'clients.errors.updateFailed': 'Failed to update client',
    
    // Agents
    'agents.title': 'Agents',
    'agents.subtitle': 'Manage your inspection team',
    'agents.addAgent': 'Add Agent',
    'agents.searchPlaceholder': 'Search agents...',
    'agents.filter': 'Filter',
    'agents.agent': 'Agent',
    'agents.contact': 'Contact',
    'agents.performance': 'Performance',
    'agents.status': 'Status',
    'agents.actions': 'Actions',
    'agents.completed': 'Completed',
    'agents.load': 'Load',
    'agents.email': 'Email',
    'agents.call': 'Call',
    'agents.edit': 'Edit',
    'agents.delete': 'Delete',
    'agents.noAgents': 'No agents added yet. Click \'Add Agent\' to get started.',
    'agents.noResults': 'No agents found matching your search.',

    // Agent Edit Modal
    'agents.editAgent.title': 'Edit Agent',
    'agents.editAgent.subtitle': 'Update agent information',
    'agents.editAgent.basicInfo': 'Basic Information',
    'agents.editAgent.firstName': 'First Name',
    'agents.editAgent.firstNamePlaceholder': 'John',
    'agents.editAgent.lastName': 'Last Name',
    'agents.editAgent.lastNamePlaceholder': 'Doe',
    'agents.editAgent.contactInfo': 'Contact Information',
    'agents.editAgent.email': 'Email Address',
    'agents.editAgent.emailPlaceholder': 'john.doe@example.com',
    'agents.editAgent.phone': 'Phone Number',
    'agents.editAgent.phonePlaceholder': '+41 44 123 45 67',
    'agents.editAgent.addressInfo': 'Address Information',
    'agents.editAgent.streetAddress': 'Street Address',
    'agents.editAgent.streetPlaceholder': '123 Main Street',
    'agents.editAgent.city': 'City',
    'agents.editAgent.cityPlaceholder': 'Zurich',
    'agents.editAgent.state': 'State/Province',
    'agents.editAgent.statePlaceholder': 'ZH',
    'agents.editAgent.zipCode': 'ZIP/Postal Code',
    'agents.editAgent.zipPlaceholder': '8001',
    'agents.editAgent.country': 'Country',
    'agents.editAgent.countryPlaceholder': 'Switzerland',
    'agents.editAgent.professionalInfo': 'Professional Information',
    'agents.editAgent.licenseNumber': 'License Number',
    'agents.editAgent.licensePlaceholder': 'LIC-123456',
    'agents.editAgent.experience': 'Experience (years)',
    'agents.editAgent.experiencePlaceholder': '5',
    'agents.editAgent.commissionRate': 'Commission Rate (%)',
    'agents.editAgent.commissionPlaceholder': '10',
    'agents.editAgent.specializations': 'Specializations',
    'agents.editAgent.languages': 'Languages',
    'agents.editAgent.statusPerformance': 'Status & Performance',
    'agents.editAgent.status': 'Status',
    'agents.editAgent.statusActive': 'Active',
    'agents.editAgent.statusBusy': 'Busy',
    'agents.editAgent.statusUnavailable': 'Unavailable',
    'agents.editAgent.statusInactive': 'Inactive',
    'agents.editAgent.bio': 'Bio',
    'agents.editAgent.bioPlaceholder': "Tell us about the agent's experience and expertise...",
    'agents.editAgent.cancel': 'Cancel',
    'agents.editAgent.update': 'Update Agent',
    'agents.editAgent.updating': 'Updating Agent...',
    'agents.editAgent.messages.updateSuccess': 'Agent updated successfully!',
    'agents.editAgent.errors.agentIdNotFound': 'Agent ID not found',
    'agents.editAgent.errors.fillRequiredFields': 'Please fill in all required fields',
    'agents.editAgent.errors.validEmail': 'Please enter a valid email address',
    'agents.editAgent.errors.validPhone': 'Please enter a valid phone number',
    'agents.editAgent.errors.updateFailed': 'Failed to update agent',
    
    // Scheduling
    'scheduling.title': 'Scheduling',
    'scheduling.subtitle': 'Manage inspection appointments',
    'scheduling.scheduleInspection': 'Schedule Inspection',
    'scheduling.showCompleted': 'Show Completed',
    'scheduling.showUpcoming': 'Show Upcoming',
    'scheduling.dateTime': 'Date & Time',
    'scheduling.property': 'Property',
    'scheduling.client': 'Client',
    'scheduling.contact': 'Contact',
    'scheduling.agent': 'Agent',
    'scheduling.type': 'Type',
    'scheduling.status': 'Status',
    'scheduling.actions': 'Actions',
    'scheduling.edit': 'Edit',
    'scheduling.remove': 'Remove',
    'scheduling.noInspections': 'No inspections scheduled',
    'scheduling.addInspection': 'Add Inspection',
    'scheduling.completedInspections': 'Completed Inspections',
    'scheduling.upcomingInspections': 'Upcoming Inspections',
    'scheduling.showing': 'Showing',
    'scheduling.completed': 'completed',
    'scheduling.upcoming': 'upcoming',
    'scheduling.inspections': 'inspections',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.name': 'Name',
    'common.type': 'Type',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.notes': 'Notes',
    'common.description': 'Description',
    'common.price': 'Price',
    'common.size': 'Size',
    'common.bedrooms': 'Bedrooms',
    'common.bathrooms': 'Bathrooms',
    'common.squareFeet': 'Square Feet',
    'common.perMonth': 'per month',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.available': 'Available',
    'common.occupied': 'Occupied',
    'common.maintenance': 'Maintenance',
    'common.unavailable': 'Unavailable',
    'common.scheduled': 'Scheduled',
    'common.completed': 'Completed',
    'common.inProgress': 'In Progress',
    'common.pending': 'Pending',
    'common.overdue': 'Overdue',
    'common.cancelled': 'Cancelled',
    'common.busy': 'Busy',
    'common.prospect': 'Prospect',
    'common.defects': 'Defects',
    'common.pdf': 'PDF',
    'common.noAddress': 'No address',
    'common.noCity': 'No city',
    'common.noContactInfo': 'No contact info',
    'common.noSpecialties': 'No specialties',
    'common.more': 'more',
    'common.defect': 'defect',
    'common.defects': 'defects',
    'common.callClient': 'Call Client',
    'common.emailClient': 'Email Client',
    'common.phoneNumberCopied': 'Phone number copied to clipboard',
    'common.emailCopied': 'Email copied to clipboard',
    'common.completing': 'Completing...',
    'common.complete': 'Complete',
    'common.cancelInspection': 'Cancel Inspection',
    'common.markAsCompleted': 'Mark as Completed',
    'common.editInspection': 'Edit Inspection',
    'common.callPhone': 'Call phone',
    'common.editClient': 'Edit client',
    'common.deleteClient': 'Delete client',
    'common.editAgent': 'Edit agent',
    'common.deleteAgent': 'Delete agent',
    'common.editProperty': 'Edit Property',
    'common.deleteProperty': 'Delete Property',
    'common.viewProperty': 'View Property',
    'common.screenSizeNotSupported': 'Screen Size Not Supported',
    'common.screenSizeMessage': 'This application is optimized for desktop use and requires a screen width of at least 1024px for the best experience.',
    'common.screenSizeInstruction': 'Please access this dashboard from a desktop or laptop computer with a wider screen.',
    'common.agentAccessRestricted': 'Access Restricted',
    'common.agentAccessMessage': 'This web dashboard is only available for administrators. Agents should use the mobile application.',
    'common.agentAccessInstruction': 'Please use the React Native mobile app to access your agent features.',
    'common.signOut': 'Sign Out',
  },
  de: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.properties': 'Immobilien',
    'nav.clients': 'Kunden',
    'nav.agents': 'Mitarbeiter',
    'nav.scheduling': 'Terminplanung',
    'nav.reports': 'Berichte',
    'nav.notifications': 'Benachrichtigungen',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Übersicht der Immobilieninspektion',
    'dashboard.totalProperties': 'Gesamte Immobilien',
    'dashboard.activeInspections': 'Aktive Inspektionen',
    'dashboard.completedInspections': 'Abgeschlossene Inspektionen',
    'dashboard.totalClients': 'Gesamte Kunden',
    'dashboard.availableAgents': 'Mitarbeiter',
    'dashboard.recentActivity': 'Letzte Aktivitäten',
    'dashboard.upcomingInspections': 'Anstehende Inspektionen',
    'dashboard.noProperties': 'Noch keine Immobilien',
    'dashboard.propertiesPortfolio': 'Immobilien in Ihrem Portfolio',
    'dashboard.noClients': 'Noch keine Kunden',
    'dashboard.activeClients': 'Aktive Kundenbeziehungen',
    'dashboard.noAgents': 'Noch keine Mitarbeiter',
    'dashboard.agentsReady': 'Mitarbeiter bereit für Inspektionen',
    'dashboard.noPending': 'Keine ausstehenden Inspektionen',
    'dashboard.scheduledInspections': 'Termine',
    'dashboard.inspectionOverview': 'Inspektionsübersicht',
    'dashboard.monthlyOverview': 'Monatliche abgeschlossene vs. geplante Inspektionen',
    'dashboard.noInspectionData': 'Keine Inspektionsdaten verfügbar',
    'dashboard.chartWillAppear': 'Diagramm wird angezeigt, wenn Inspektionsdaten verfügbar sind',
    'dashboard.quickActions': 'Schnellaktionen',
    'dashboard.addProperty': 'Immobilie hinzufügen',
    'dashboard.addClient': 'Kunde hinzufügen',
    'dashboard.scheduleInspection': 'Inspektion planen',
    'dashboard.addAgent': 'Mitarbeiter hinzufügen',
    'dashboard.recentInspections': 'Letzte Inspektionen',
    'dashboard.latestActivities': 'Neueste Inspektionsaktivitäten',
    'dashboard.noUpcomingInspections': 'Keine anstehenden Inspektionen',
    'dashboard.upcomingActivitiesWillAppear': 'Anstehende Aktivitäten werden hier angezeigt',
    'dashboard.status.completed': 'abgeschlossen',
    'dashboard.status.upcoming': 'anstehend',
    'dashboard.viewAll': 'Alle anzeigen',
    'dashboard.appointment': 'Termin',
    'dashboard.client': 'Kunde',
    'dashboard.agent': 'Mitarbeiter',
    'dashboard.date': 'Datum',
    'dashboard.status': 'Status',
    'dashboard.noRecentInspections': 'Keine letzten Inspektionen',
    'dashboard.recentActivitiesWillAppear': 'Letzte Inspektionsaktivitäten werden hier angezeigt',
    
    // Properties
    'properties.title': 'Immobilien',
    'properties.subtitle': 'Verwalten Sie Ihr Immobilienportfolio',
    'properties.addProperty': 'Immobilie hinzufügen',
    'properties.searchPlaceholder': 'Immobilien suchen...',
    'properties.filter': 'Filter',
    'properties.property': 'Immobilie',
    'properties.address': 'Adresse',
    'properties.details': 'Details',
    'properties.rentPrice': 'Mietpreis',
    'properties.status': 'Status',
    'properties.actions': 'Aktionen',
    'properties.view': 'Anzeigen',
    'properties.edit': 'Bearbeiten',
    'properties.delete': 'Löschen',
    'properties.noProperties': 'Noch keine Immobilien hinzugefügt. Klicken Sie auf \'Immobilie hinzufügen\', um zu beginnen.',
    'properties.noResults': 'Keine Immobilien gefunden, die Ihrer Suche entsprechen.',
    'properties.detail.propertyDetails': 'Immobiliendetails',
    'properties.detail.subtitle': 'Detaillierte Informationen zu dieser Immobilie anzeigen',
    'properties.detail.summary': 'Zusammenfassung',
    'properties.detail.address': 'Adresse',
    'properties.detail.totalUnits': 'Gesamte Einheiten',
    'properties.detail.manager': 'Verwalter',
    'properties.detail.hierarchicalStructure': 'Hierarchische Struktur',
    'properties.detail.noStructure': 'Keine hierarchische Struktur für diese Immobilie definiert',
    'properties.detail.entrance': 'Eingang',
    'properties.detail.floor': 'Etage',
    'properties.detail.floors': 'Etagen',
    'properties.detail.unit': 'Einheit',
    'properties.detail.units': 'Einheiten',
    'properties.detail.unitType.apartment': 'Wohnung',
    'properties.detail.unitType.office': 'Büro',
    'properties.detail.unitType.parking': 'Parkplatz',
    'properties.detail.unitType.storage': 'Lager',
    'properties.detail.documentsContracts': 'Dokumente & Verträge',
    'properties.detail.noDocuments': 'Keine Dokumente verfügbar',
    'properties.detail.documentType.contract': 'Vertrag',
    'properties.detail.documentType.document': 'Dokument',
    'properties.detail.documentType.other': 'Sonstiges',
    'properties.detail.view': 'Anzeigen',
    'properties.detail.interventionHistory': 'Eingriffsverlauf',
    'properties.detail.noInterventions': 'Keine Eingriffe aufgezeichnet',
    'properties.detail.performedBy': 'Durchgeführt von',
    'properties.detail.cost': 'Kosten',
    'properties.detail.notFound': 'Immobilie nicht gefunden',
    'properties.detail.unitsTable': 'Einheiten',
    'properties.detail.noUnits': 'Noch keine Einheiten hinzugefügt',
    'properties.detail.location': 'Standort',
    'properties.detail.type': 'Typ',
    'properties.detail.details': 'Details',
    'properties.detail.size': 'Größe',
    'properties.detail.status': 'Status',
    'properties.detail.addUnitButton': 'Einheit hinzufügen',
    'properties.detail.addUnit.title': 'Einheit hinzufügen',
    'properties.detail.addUnit.subtitle': 'Neue Einheit innerhalb dieser Immobilie erstellen',
    'properties.detail.addUnit.entranceName': 'Eingangsname oder -nummer',
    'properties.detail.addUnit.entrancePlaceholder': 'Eingang A',
    'properties.detail.addUnit.floorNumber': 'Etagen-Nummer',
    'properties.detail.addUnit.floorPlaceholder': '1',
    'properties.detail.addUnit.unitNumber': 'Einheitsnummer',
    'properties.detail.addUnit.validation': 'Bitte füllen Sie alle Pflichtfelder aus',
    'properties.detail.addUnit.success': 'Einheit erfolgreich hinzugefügt!',
    'properties.detail.addUnit.error': 'Einheit konnte nicht hinzugefügt werden',
    'properties.detail.addUnit.save': 'Einheit speichern',
    'properties.detail.addUnit.saving': 'Wird gespeichert...',
    'properties.detail.addUnit.tenant': 'Mieter',
    'properties.detail.addUnit.notes': 'Notizen',
    'properties.detail.addUnit.notesPlaceholder': 'Zusätzliche Notizen zu dieser Einheit',
    'properties.detail.addDocumentButton': 'Dokument hinzufügen',
    'properties.detail.addDocument.title': 'Dokument hochladen',
    'properties.detail.addDocument.subtitle': 'Laden Sie ein Dokument oder einen Vertrag für diese Immobilie hoch',
    'properties.detail.addDocument.name': 'Dokumentname',
    'properties.detail.addDocument.namePlaceholder': 'z.B. Mietvertrag, Versicherungspolice',
    'properties.detail.addDocument.type': 'Dokumenttyp',
    'properties.detail.addDocument.file': 'PDF-Datei',
    'properties.detail.addDocument.filePlaceholder': 'Klicken Sie, um PDF-Dokument hochzuladen',
    'properties.detail.addDocument.fileHint': 'Nur PDF-Dateien, max. 10MB',
    'properties.detail.addDocument.upload': 'Dokument hochladen',
    'properties.detail.addDocument.uploading': 'Wird hochgeladen...',
    'properties.detail.addDocument.success': 'Dokument erfolgreich hochgeladen',
    'properties.detail.addDocument.errors.fillRequired': 'Bitte füllen Sie alle erforderlichen Felder aus',
    'properties.detail.addDocument.errors.uploadFailed': 'Dokument konnte nicht hochgeladen werden',
    
    // Clients
    'clients.title': 'Kunden',
    'clients.subtitle': 'Verwalten Sie Ihre Kundenbeziehungen',
    'clients.addClient': 'Kunde hinzufügen',
    'clients.searchPlaceholder': 'Kunden suchen...',
    'clients.filter': 'Filter',
    'clients.client': 'Kunde',
    'clients.contact': 'Kontakt',
    'clients.address': 'Adresse',
    'clients.status': 'Status',
    'clients.actions': 'Aktionen',
    'clients.email': 'E-Mail',
    'clients.call': 'Anrufen',
    'clients.edit': 'Bearbeiten',
    'clients.delete': 'Löschen',
    'clients.noClients': 'Noch keine Kunden hinzugefügt. Klicken Sie auf \'Kunde hinzufügen\', um zu beginnen.',
    'clients.noResults': 'Keine Kunden gefunden, die Ihrer Suche entsprechen.',
    
    // Client Edit Modal
    'clients.editClient.title': 'Kunde bearbeiten',
    'clients.editClient.subtitle': 'Kundeninformationen aktualisieren',
    'clients.editClient.basicInfo': 'Grundinformationen',
    'clients.editClient.firstName': 'Vorname',
    'clients.editClient.firstNamePlaceholder': 'Max',
    'clients.editClient.lastName': 'Nachname',
    'clients.editClient.lastNamePlaceholder': 'Mustermann',
    'clients.editClient.contactInfo': 'Kontaktinformationen',
    'clients.editClient.email': 'E-Mail-Adresse',
    'clients.editClient.emailPlaceholder': 'max.mustermann@beispiel.de',
    'clients.editClient.phone': 'Telefonnummer',
    'clients.editClient.phonePlaceholder': '+41 44 123 45 67',
    'clients.editClient.addressInfo': 'Adressinformationen',
    'clients.editClient.streetAddress': 'Straßenadresse',
    'clients.editClient.streetPlaceholder': 'Musterstraße 123',
    'clients.editClient.city': 'Stadt',
    'clients.editClient.cityPlaceholder': 'Zürich',
    'clients.editClient.state': 'Kanton/Bundesland',
    'clients.editClient.statePlaceholder': 'ZH',
    'clients.editClient.zipCode': 'PLZ/Postleitzahl',
    'clients.editClient.zipPlaceholder': '8001',
    'clients.editClient.country': 'Land',
    'clients.editClient.countryPlaceholder': 'Schweiz',
    'clients.editClient.status': 'Kundenstatus',
    'clients.editClient.statusActive': 'Aktiv',
    'clients.editClient.statusInactive': 'Inaktiv',
    'clients.editClient.statusProspect': 'Interessent',
    'clients.editClient.additionalInfo': 'Zusätzliche Informationen',
    'clients.editClient.notes': 'Notizen',
    'clients.editClient.notesPlaceholder': 'Fügen Sie zusätzliche Notizen zu diesem Kunden hinzu...',
    'clients.editClient.cancel': 'Abbrechen',
    'clients.editClient.update': 'Kunde aktualisieren',
    'clients.editClient.updating': 'Kunde wird aktualisiert...',
    
    // Client Messages and Errors
    'clients.messages.updateSuccess': 'Kunde erfolgreich aktualisiert!',
    'clients.errors.clientIdNotFound': 'Kunden-ID nicht gefunden',
    'clients.errors.fillRequiredFields': 'Bitte füllen Sie alle erforderlichen Felder aus',
    'clients.errors.validEmail': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
    'clients.errors.validPhone': 'Bitte geben Sie eine gültige Telefonnummer ein',
    'clients.errors.updateFailed': 'Kunde konnte nicht aktualisiert werden',
    
    // Agents
    'agents.title': 'Mitarbeiter',
    'agents.subtitle': 'Verwalten Sie Ihr Inspektionsteam',
    'agents.addAgent': 'Mitarbeiter hinzufügen',
    'agents.searchPlaceholder': 'Mitarbeiter suchen...',
    'agents.filter': 'Filter',
    'agents.agent': 'Mitarbeiter',
    'agents.contact': 'Kontakt',
    'agents.performance': 'Leistung',
    'agents.status': 'Status',
    'agents.actions': 'Aktionen',
    'agents.completed': 'Abgeschlossen',
    'agents.load': 'Belastung',
    'agents.email': 'E-Mail',
    'agents.call': 'Anrufen',
    'agents.edit': 'Bearbeiten',
    'agents.delete': 'Löschen',
    'agents.noAgents': 'Noch keine Mitarbeiter hinzugefügt. Klicken Sie auf \'Mitarbeiter hinzufügen\', um zu beginnen.',
    'agents.noResults': 'Keine Mitarbeiter gefunden, die Ihrer Suche entsprechen.',

    // Agent Edit Modal
    'agents.editAgent.title': 'Mitarbeiter bearbeiten',
    'agents.editAgent.subtitle': 'Mitarbeiterinformationen aktualisieren',
    'agents.editAgent.basicInfo': 'Grundinformationen',
    'agents.editAgent.firstName': 'Vorname',
    'agents.editAgent.firstNamePlaceholder': 'Max',
    'agents.editAgent.lastName': 'Nachname',
    'agents.editAgent.lastNamePlaceholder': 'Mustermann',
    'agents.editAgent.contactInfo': 'Kontaktinformationen',
    'agents.editAgent.email': 'E-Mail-Adresse',
    'agents.editAgent.emailPlaceholder': 'max.mustermann@beispiel.de',
    'agents.editAgent.phone': 'Telefonnummer',
    'agents.editAgent.phonePlaceholder': '+41 44 123 45 67',
    'agents.editAgent.addressInfo': 'Adressinformationen',
    'agents.editAgent.streetAddress': 'Straßenadresse',
    'agents.editAgent.streetPlaceholder': 'Musterstraße 123',
    'agents.editAgent.city': 'Stadt',
    'agents.editAgent.cityPlaceholder': 'Zürich',
    'agents.editAgent.state': 'Kanton/Bundesland',
    'agents.editAgent.statePlaceholder': 'ZH',
    'agents.editAgent.zipCode': 'PLZ/Postleitzahl',
    'agents.editAgent.zipPlaceholder': '8001',
    'agents.editAgent.country': 'Land',
    'agents.editAgent.countryPlaceholder': 'Schweiz',
    'agents.editAgent.professionalInfo': 'Berufliche Informationen',
    'agents.editAgent.licenseNumber': 'Lizenznummer',
    'agents.editAgent.licensePlaceholder': 'LIC-123456',
    'agents.editAgent.experience': 'Erfahrung (Jahre)',
    'agents.editAgent.experiencePlaceholder': '5',
    'agents.editAgent.commissionRate': 'Provisionssatz (%)',
    'agents.editAgent.commissionPlaceholder': '10',
    'agents.editAgent.specializations': 'Spezialisierungen',
    'agents.editAgent.languages': 'Sprachen',
    'agents.editAgent.statusPerformance': 'Status & Leistung',
    'agents.editAgent.status': 'Status',
    'agents.editAgent.statusActive': 'Aktiv',
    'agents.editAgent.statusBusy': 'Beschäftigt',
    'agents.editAgent.statusUnavailable': 'Nicht verfügbar',
    'agents.editAgent.statusInactive': 'Inaktiv',
    'agents.editAgent.bio': 'Biografie',
    'agents.editAgent.bioPlaceholder': 'Beschreiben Sie die Erfahrung und Expertise des Mitarbeiters...',
    'agents.editAgent.cancel': 'Abbrechen',
    'agents.editAgent.update': 'Mitarbeiter aktualisieren',
    'agents.editAgent.updating': 'Mitarbeiter wird aktualisiert...',
    'agents.editAgent.messages.updateSuccess': 'Mitarbeiter erfolgreich aktualisiert!',
    'agents.editAgent.errors.agentIdNotFound': 'Mitarbeiter-ID nicht gefunden',
    'agents.editAgent.errors.fillRequiredFields': 'Bitte füllen Sie alle erforderlichen Felder aus',
    'agents.editAgent.errors.validEmail': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
    'agents.editAgent.errors.validPhone': 'Bitte geben Sie eine gültige Telefonnummer ein',
    'agents.editAgent.errors.updateFailed': 'Mitarbeiter konnte nicht aktualisiert werden',
    
    // Scheduling
    'scheduling.title': 'Terminplanung',
    'scheduling.subtitle': 'Verwalten Sie Inspektionstermine',
    'scheduling.scheduleInspection': 'Inspektion planen',
    'scheduling.showCompleted': 'Abgeschlossene anzeigen',
    'scheduling.showUpcoming': 'Anstehende anzeigen',
    'scheduling.dateTime': 'Datum & Zeit',
    'scheduling.property': 'Immobilie',
    'scheduling.client': 'Kunde',
    'scheduling.contact': 'Kontakt',
    'scheduling.agent': 'Mitarbeiter',
    'scheduling.type': 'Typ',
    'scheduling.status': 'Status',
    'scheduling.actions': 'Aktionen',
    'scheduling.edit': 'Bearbeiten',
    'scheduling.remove': 'Entfernen',
    'scheduling.noInspections': 'Keine Inspektionen geplant',
    'scheduling.addInspection': 'Inspektion hinzufügen',
    'scheduling.completedInspections': 'Abgeschlossene Inspektionen',
    'scheduling.upcomingInspections': 'Anstehende Inspektionen',
    'scheduling.showing': 'Anzeigen',
    'scheduling.completed': 'abgeschlossene',
    'scheduling.upcoming': 'anstehende',
    'scheduling.inspections': 'Inspektionen',
    
    // Common
    'common.loading': 'Laden...',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.view': 'Anzeigen',
    'common.add': 'Hinzufügen',
    'common.search': 'Suchen',
    'common.filter': 'Filter',
    'common.status': 'Status',
    'common.actions': 'Aktionen',
    'common.email': 'E-Mail',
    'common.phone': 'Telefon',
    'common.address': 'Adresse',
    'common.name': 'Name',
    'common.type': 'Typ',
    'common.date': 'Datum',
    'common.time': 'Zeit',
    'common.notes': 'Notizen',
    'common.description': 'Beschreibung',
    'common.price': 'Preis',
    'common.size': 'Größe',
    'common.bedrooms': 'Schlafzimmer',
    'common.bathrooms': 'Badezimmer',
    'common.squareFeet': 'Quadratmeter',
    'common.perMonth': 'pro Monat',
    'common.active': 'Aktiv',
    'common.inactive': 'Inaktiv',
    'common.available': 'Verfügbar',
    'common.occupied': 'Besetzt',
    'common.maintenance': 'Wartung',
    'common.unavailable': 'Nicht verfügbar',
    'common.scheduled': 'Geplant',
    'common.completed': 'Abgeschlossen',
    'common.inProgress': 'In Bearbeitung',
    'common.pending': 'Ausstehend',
    'common.overdue': 'Überfällig',
    'common.cancelled': 'Storniert',
    'common.busy': 'Beschäftigt',
    'common.prospect': 'Interessent',
    'common.defects': 'Mängel',
    'common.pdf': 'PDF',
    'common.noAddress': 'Keine Adresse',
    'common.noCity': 'Keine Stadt',
    'common.noContactInfo': 'Keine Kontaktinformationen',
    'common.noSpecialties': 'Keine Spezialisierungen',
    'common.more': 'weitere',
    'common.defect': 'Mangel',
    'common.defects': 'Mängel',
    'common.callClient': 'Kunde anrufen',
    'common.phoneNumberCopied': 'Telefonnummer in die Zwischenablage kopiert',
    'common.emailCopied': 'E-Mail in die Zwischenablage kopiert',
    'common.completing': 'Wird abgeschlossen...',
    'common.complete': 'Abschließen',
    'common.cancelInspection': 'Inspektion stornieren',
    'common.markAsCompleted': 'Als abgeschlossen markieren',
    'common.editInspection': 'Inspektion bearbeiten',
    'common.sendEmail': 'E-Mail senden',
    'common.callPhone': 'Telefon anrufen',
    'common.editClient': 'Kunde bearbeiten',
    'common.deleteClient': 'Kunde löschen',
    'common.editAgent': 'Mitarbeiter bearbeiten',
    'common.deleteAgent': 'Mitarbeiter löschen',
    'common.editProperty': 'Immobilie bearbeiten',
    'common.deleteProperty': 'Immobilie löschen',
    'common.viewProperty': 'Immobilie anzeigen',
    'common.screenSizeNotSupported': 'Bildschirmgröße nicht unterstützt',
    'common.screenSizeMessage': 'Diese Anwendung ist für die Desktop-Nutzung optimiert und erfordert eine Bildschirmbreite von mindestens 1024px für die beste Erfahrung.',
    'common.screenSizeInstruction': 'Bitte greifen Sie auf dieses Dashboard von einem Desktop- oder Laptop-Computer mit einem breiteren Bildschirm zu.',
    'common.agentAccessRestricted': 'Zugang eingeschränkt',
    'common.agentAccessMessage': 'Dieses Web-Dashboard ist nur für Administratoren verfügbar. Mitarbeiter sollten die mobile Anwendung verwenden.',
    'common.agentAccessInstruction': 'Bitte verwenden Sie die React Native Mobile App, um auf Ihre Mitarbeiter-Funktionen zuzugreifen.',
    'common.signOut': 'Abmelden',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'de')) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language to localStorage when it changes
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
